export const COUNTRY_CODE_MAP: Record<string, string> = {
  "albania": "AL",
  "algeria": "DZ",
  "american samoa": "AS",
  "angola": "AO",
  "antigua and barbuda": "AG",
  "argentina": "AR",
  "aruba": "AW",
  "australia": "AU",
  "bahamas": "BS",
  "bahamas, the": "BS",
  "bahrain": "BH",
  "bangladesh": "BD",
  "barbados": "BB",
  "belgium": "BE",
  "belize": "BZ",
  "benin": "BJ",
  "bermuda": "BM",
  "brasil": "BR",
  "brazil": "BR",
  "britain": "GB",
  "british virgin islands": "VG",
  "brunei darussalam": "BN",
  "bulgaria": "BG",
  "cabo verde": "CV",
  "cambodia": "KH",
  "cameroon": "CM",
  "canada": "CA",
  "chile": "CL",
  "china": "CN",
  "colombia": "CO",
  "comoros": "KM",
  "congo": "CG",
  "congo, dem. rep.": "CD",
  "congo, rep.": "CG",
  "costa rica": "CR",
  "cote d'ivoire": "CI",
  "croatia": "HR",
  "cuba": "CU",
  "curacao": "CW",
  "cyprus": "CY",
  "côte d'ivoire": "CI",
  "democratic republic of the congo": "CD",
  "denmark": "DK",
  "djibouti": "DJ",
  "dominica": "DM",
  "dominican republic": "DO",
  "dr congo": "CD",
  "drc": "CD",
  "ecuador": "EC",
  "egypt": "EG",
  "el salvador": "SV",
  "equatorial guinea": "GQ",
  "eritrea": "ER",
  "estonia": "EE",
  "faroe islands": "FO",
  "fiji": "FJ",
  "finland": "FI",
  "france": "FR",
  "french polynesia": "PF",
  "gabon": "GA",
  "gambia": "GM",
  "gambia, the": "GM",
  "georgia": "GE",
  "germany": "DE",
  "ghana": "GH",
  "gibraltar": "GI",
  "great britain": "GB",
  "greece": "GR",
  "greenland": "GL",
  "grenada": "GD",
  "guam": "GU",
  "guatemala": "GT",
  "guinea": "GN",
  "guinea-bissau": "GW",
  "guyana": "GY",
  "haiti": "HT",
  "honduras": "HN",
  "hong kong": "HK",
  "hong kong sar": "HK",
  "iceland": "IS",
  "india": "IN",
  "indonesia": "ID",
  "iran": "IR",
  "iran, islamic republic of": "IR",
  "iraq": "IQ",
  "ireland": "IE",
  "israel": "IL",
  "italy": "IT",
  "ivory coast": "CI",
  "jamaica": "JM",
  "japan": "JP",
  "jordan": "JO",
  "kenya": "KE",
  "kiribati": "KI",
  "korea": "KR",
  "kuwait": "KW",
  "latvia": "LV",
  "lebanon": "LB",
  "liberia": "LR",
  "libya": "LY",
  "lithuania": "LT",
  "macao": "MO",
  "macau": "MO",
  "madagascar": "MG",
  "malaysia": "MY",
  "maldives": "MV",
  "malta": "MT",
  "marshall islands": "MH",
  "mauritania": "MR",
  "mauritius": "MU",
  "mexico": "MX",
  "micronesia, fed. sts.": "FM",
  "moldova": "MD",
  "montenegro": "ME",
  "morocco": "MA",
  "mozambique": "MZ",
  "myanmar": "MM",
  "namibia": "NA",
  "nauru": "NR",
  "netherlands": "NL",
  "new caledonia": "NC",
  "new zealand": "NZ",
  "nicaragua": "NI",
  "nigeria": "NG",
  "northern mariana islands": "MP",
  "norway": "NO",
  "oman": "OM",
  "pakistan": "PK",
  "palau": "PW",
  "palestine": "PS",
  "panama": "PA",
  "papua new guinea": "PG",
  "paraguay": "PY",
  "peru": "PE",
  "philippines": "PH",
  "poland": "PL",
  "portugal": "PT",
  "puerto rico": "PR",
  "qatar": "QA",
  "republic of korea": "KR",
  "republic of moldova": "MD",
  "republic of the congo": "CG",
  "romania": "RO",
  "russia": "RU",
  "russian federation": "RU",
  "samoa": "WS",
  "saudi arabia": "SA",
  "senegal": "SN",
  "seychelles": "SC",
  "sierra leone": "SL",
  "singapore": "SG",
  "sint maarten (dutch part)": "SX",
  "slovenia": "SI",
  "solomon islands": "SB",
  "somalia": "SO",
  "south africa": "ZA",
  "south korea": "KR",
  "spain": "ES",
  "sri lanka": "LK",
  "st. kitts and nevis": "KN",
  "st. lucia": "LC",
  "st. vincent and the grenadines": "VC",
  "sudan": "SD",
  "suriname": "SR",
  "sweden": "SE",
  "switzerland": "CH",
  "syria": "SY",
  "syrian arab republic": "SY",
  "são tomé and príncipe": "ST",
  "taiwan": "TW",
  "taiwan, province of china": "TW",
  "tanzania": "TZ",
  "tanzania, united republic of": "TZ",
  "thailand": "TH",
  "timor-leste": "TL",
  "togo": "TG",
  "tonga": "TO",
  "trinidad and tobago": "TT",
  "tunisia": "TN",
  "turkey": "TR",
  "tuvalu": "TV",
  "u.s.": "US",
  "u.s.a.": "US",
  "uae": "AE",
  "uk": "GB",
  "ukraine": "UA",
  "united arab emirates": "AE",
  "united kingdom": "GB",
  "united states": "US",
  "united states of america": "US",
  "uruguay": "UY",
  "us": "US",
  "usa": "US",
  "vanuatu": "VU",
  "venezuela": "VE",
  "venezuela, rb": "VE",
  "viet nam": "VN",
  "vietnam": "VN",
  "yemen": "YE",
  "yemen, rep.": "YE",
};

export function countryToCode(name: string | null | undefined): string {
  if (!name) return "";
  return COUNTRY_CODE_MAP[name.trim().toLowerCase()] ?? "";
}
