export const COUNTRY_CODE_MAP: Record<string, string> = {
  afghanistan: "AF",
  angola: "AO",
  argentina: "AR",
  australia: "AU",
  benin: "BJ",
  bermuda: "BM",
  brazil: "BR",
  canada: "CA",
  chile: "CL",
  china: "CN",
  egypt: "EG",
  france: "FR",
  germany: "DE",
  ghana: "GH",
  "hong kong": "HK",
  india: "IN",
  israel: "IL",
  italy: "IT",
  "ivory coast": "CI",
  japan: "JP",
  jordan: "JO",
  mexico: "MX",
  mozambique: "MZ",
  netherlands: "NL",
  paraguay: "PY",
  poland: "PL",
  "saudi arabia": "SA",
  "south africa": "ZA",
  "south korea": "KR",
  spain: "ES",
  togo: "TG",
  turkey: "TR",
  "united arab emirates": "AE",
  uae: "AE",
  "united kingdom": "GB",
  uk: "GB",
  "united states": "US",
  "united states of america": "US",
  usa: "US",
  us: "US",
  uruguay: "UY",
  vietnam: "VN",
};

export function countryToCode(name: string | null | undefined): string {
  if (!name) return "";
  return COUNTRY_CODE_MAP[name.trim().toLowerCase()] ?? "";
}