import type {
  DealDetailData,
  DealStatus,
  DealJourneyStage,
  DealTimelineStage,
  DealDocumentItem,
} from "@/components/mundus/DealDetailView";
import type { BuyerOrder } from "@/hooks/useBuyerOrders";
import type { Sale } from "@/data/mockSales";

const FLAGS: Record<string, string> = {
  Brazil: "🇧🇷", "Hong Kong": "🇭🇰", China: "🇨🇳", Argentina: "🇦🇷",
  "United States": "🇺🇸", Vietnam: "🇻🇳", "Saudi Arabia": "🇸🇦",
  "United Arab Emirates": "🇦🇪", Singapore: "🇸🇬", Philippines: "🇵🇭",
  Mexico: "🇲🇽", Egypt: "🇪🇬", "Viet Nam": "🇻🇳",
};
const flag = (country?: string) => (country && FLAGS[country]) || "🌐";

function hashIdx(seed: string, mod: number) {
  let h = 0;
  for (let i = 0; i < seed.length; i++) h = (h * 31 + seed.charCodeAt(i)) | 0;
  return Math.abs(h) % mod;
}

function statusToJourney(stage: "early" | "production" | "shipped" | "delivered" | "rejected"): DealJourneyStage {
  if (stage === "delivered") return "delivered";
  if (stage === "shipped") return "in_transit";
  if (stage === "production") return "loading";
  if (stage === "rejected") return "booked";
  return "booked";
}

function genShipment(seed: string, fcls: number, totalKg: number, originPort: string, destPort: string) {
  const i = hashIdx(seed, 999);
  const vessel = ["Ever Glory", "MSC Maya", "Cosco Star", "Maersk Hudson", "Hapag Lloyd"][hashIdx(seed, 5)];
  const voyage = `${100 + (i % 400)}E`;
  const containers = Array.from({ length: fcls }, (_, k) => {
    const cNo = `${seed.slice(-4)}-C${String(k + 1).padStart(2, "0")}`;
    const each = Math.round(totalKg / fcls);
    return {
      containerNo: cNo,
      sealNo: `MNDS${100000 + i + k}`,
      booking: `BKG-${700000 + i + k}`,
      blNumber: `MNDS-BL-${String(900 + (i % 100) + k).padStart(6, "0")}`,
      vessel,
      voyage,
      portLoading: originPort,
      portDischarge: destPort,
      etd: "May 22, 2026",
      eta: "Jun 18, 2026",
      grossKg: each,
      netKg: Math.round(each * 0.97),
      temperature: "Frozen · −18°C",
    };
  });
  return containers;
}

function genNegotiation(seed: string, totalValueUsd: number) {
  const i = hashIdx(seed, 100);
  const initial = Math.round(totalValueUsd * (1.06 + (i % 7) / 100));
  const firstBid = Math.round(totalValueUsd * (0.90 + (i % 5) / 100));
  const counter1 = Math.round((initial + firstBid) / 2);
  return {
    initialAskingUsd: initial,
    firstBuyerBidUsd: firstBid,
    closedAt: "5/16/2026",
    rounds: [
      { round: 1, buyerBidUsd: firstBid, counterUsd: counter1, at: "May 11, 2026 · 14:30 EST" },
      { round: 2, buyerBidUsd: totalValueUsd, counterUsd: totalValueUsd, accepted: true, at: "May 12, 2026 · 14:30 EST" },
    ],
  };
}

function genDocuments(seed: string, dealNumber: string, completion: number): { autoGenerated: { salesOrder?: string; purchaseOrder?: string }; items: DealDocumentItem[] } {
  const all: DealDocumentItem[] = [
    { id: "ci", category: "trade", name: "Commercial Invoice", required: true },
    { id: "pl", category: "trade", name: "Packing List", required: true },
    { id: "bl", category: "shipping", name: "Bill of Lading (B/L)", required: true },
    { id: "ins", category: "shipping", name: "Insurance Certificate" },
    { id: "coa", category: "quality", name: "Certificate of Analysis", required: true },
    { id: "insp", category: "quality", name: "Inspection Report", required: true },
    { id: "hal", category: "compliance", name: "Halal Certificate" },
    { id: "vet", category: "compliance", name: "Veterinary Certificate", required: true },
  ];
  const filled = Math.min(all.length, Math.max(0, Math.round(all.length * completion)));
  return {
    autoGenerated: {
      salesOrder: `SO MNDS ${dealNumber}`,
      purchaseOrder: `MNDS PO ${70000 + hashIdx(seed, 1000)}`,
    },
    items: all.map((d, i) => i < filled ? {
      ...d,
      uploadedAt: "May 14, 2026 · 14:32 EST",
      sizeKb: 120 + i * 8,
      fileName: `${d.id.toUpperCase()}_${dealNumber}-C01.pdf`,
    } : d),
  };
}

/* ============== BUYER ORDER → DealDetailData ============== */

const BUYER_STATUS_TONE: Record<string, DealStatus["tone"]> = {
  awaiting_supplier_acceptance: "pending",
  awaiting_pre_payment: "info",
  pre_payment_confirmed: "info",
  in_production: "info",
  awaiting_balance_payment: "pending",
  shipped: "info",
  delivered: "info",
  completed: "success",
  rejected: "danger",
};

type StageKey = "early" | "production" | "shipped" | "delivered" | "rejected";
const BUYER_STAGE: Record<string, StageKey> = {
  awaiting_supplier_acceptance: "early",
  awaiting_pre_payment: "early",
  pre_payment_confirmed: "production",
  in_production: "production",
  awaiting_balance_payment: "production",
  shipped: "shipped",
  delivered: "delivered",
  completed: "delivered",
  rejected: "rejected",
};

function buyerTimeline(order: BuyerOrder, t: (k: string, fallback: string) => string): DealTimelineStage[] {
  const s = order.status;
  const stage = (after: string[], done: string[]): DealTimelineStage["tone"] => {
    if (done.includes(s)) return "success";
    if (after.includes(s)) return "info";
    return "muted";
  };
  return [
    { key: "created", label: t("dealDetail.timeline.created", "Created"), value: order.orderDate, tone: "info" },
    {
      key: "pre_payment",
      label: t("dealDetail.timeline.prePayment", "Pre-payment"),
      value: ["pre_payment_confirmed","in_production","awaiting_balance_payment","shipped","delivered","completed"].includes(s)
        ? t("dealDetail.timeline.received", "Received") : t("dealDetail.timeline.pending", "Pending"),
      tone: stage([], ["pre_payment_confirmed","in_production","awaiting_balance_payment","shipped","delivered","completed"]),
    },
    {
      key: "production",
      label: t("dealDetail.timeline.production", "Production"),
      value: ["in_production","awaiting_balance_payment"].includes(s) ? t("dealDetail.timeline.inProgress", "In progress")
        : ["shipped","delivered","completed"].includes(s) ? t("dealDetail.timeline.done", "Done")
        : t("dealDetail.timeline.pending", "Pending"),
      tone: stage(["in_production","awaiting_balance_payment"], ["shipped","delivered","completed"]),
    },
    {
      key: "shipment",
      label: t("dealDetail.timeline.shipment", "Shipment"),
      value: s === "shipped" ? t("dealDetail.timeline.inTransit", "In transit")
        : ["delivered","completed"].includes(s) ? t("dealDetail.timeline.done", "Done")
        : t("dealDetail.timeline.pending", "Pending"),
      tone: stage(["shipped"], ["delivered","completed"]),
    },
    {
      key: "delivery",
      label: t("dealDetail.timeline.delivery", "Delivery"),
      value: ["delivered","completed"].includes(s) ? t("dealDetail.timeline.delivered", "Delivered")
        : t("dealDetail.timeline.pending", "Pending"),
      tone: stage([], ["delivered","completed"]),
    },
  ];
}

export function buyerOrderToDeal(
  order: BuyerOrder,
  t: (k: string, fallback: string) => string,
): DealDetailData {
  const totalValueUsd = order.quantityKg * order.pricePerKg;
  const COMPLETION_MAP: Record<string, number> = {
    pending_supplier: 0, awaiting_supplier_acceptance: 0,
    supplier_accepted: 0.05,
    awaiting_pre_payment: 0.1, awaiting_payment: 0.1,
    pre_payment_received: 0.2, pre_payment_confirmed: 0.2,
    in_production: 0.3,
    ready_to_ship: 0.4, booked: 0.5, stuffed: 0.55,
    awaiting_balance_payment: 0.45, awaiting_balance: 0.45,
    shipped: 0.7, in_transit: 0.75, arrived: 0.8, customs_clearance: 0.85,
    delivered: 0.9, completed: 1,
    rejected: 0, cancelled: 0, on_hold: 0.1,
  };
  const completion = COMPLETION_MAP[order.status] ?? 0;
  const stage = BUYER_STAGE[order.status];
  return {
    role: "buyer",
    dealNumber: order.orderNumber,
    date: order.orderDate,
    fcls: order.fcls,
    totalKg: order.quantityKg,
    product: order.product,
    totalValueUsd,
    status: {
      label: t(`buyer.orders.status.${order.status}`, order.status),
      tone: BUYER_STATUS_TONE[order.status] ?? "info",
    },
    rawStatus: order.status,
    statusUpdatedAt: order.updatedAt,
    party: {
      name: order.supplierName,
      country: order.origin,
      flagEmoji: flag(order.origin),
    },
    overview: {
      date: order.orderDate,
      totalValueUsd,
      origin: order.origin,
      destination: order.destination,
      incoterm: order.incoterm,
      container: `${order.fcls}× ${order.fclSize} FCL`,
      totalVolume: `${new Intl.NumberFormat("de-DE").format(order.quantityKg)} kg`,
      shipmentMonth: order.shipmentMonth,
      species: "Beef",
      temperature: "Frozen · −18°C",
    },
    cuts: [{
      name: order.product,
      weightKg: order.quantityKg,
      pricePerKgUsd: order.pricePerKg,
      subItems: order.product.toLowerCase().includes("mixed")
        ? ["Ribeye", "Striploin", "Tenderloin", "Top Sirloin"] : undefined,
    }],
    timeline: buyerTimeline(order, t),
    negotiation: genNegotiation(order.orderNumber, totalValueUsd),
    containers: genShipment(order.orderNumber, order.fcls, order.quantityKg, "Santos", order.destination),
    journeyStage: statusToJourney(stage),
    documents: genDocuments(order.orderNumber, order.orderNumber, completion),
    backHref: "/buyer/orders",
    fullNegotiationHref: undefined,
    orderId: order.id,
    shipmentReadOnly: true,
  };
}

/* ============== SUPPLIER SALE → DealDetailData ============== */

const SUPPLIER_STATUS_TONE: Record<string, DealStatus["tone"]> = {
  pending_supplier: "pending",
  awaiting_pre_payment: "info",
  supplier_accepted: "info",
  in_production: "info",
  shipped: "info",
  delivered: "success",
  completed: "success",
  cancelled: "danger",
};

function supplierTimeline(sale: Sale, t: (k: string, fallback: string) => string): DealTimelineStage[] {
  const isAwaitingAcc = sale.status === "pending_supplier";
  return [
    { key: "created", label: t("dealDetail.timeline.created", "Created"), value: sale.orderDate, tone: "info" },
    { key: "pre_payment", label: t("dealDetail.timeline.prePayment", "Pre-payment"),
      value: isAwaitingAcc ? t("dealDetail.timeline.pending", "Pending") : t("dealDetail.timeline.received", "Received"),
      tone: isAwaitingAcc ? "muted" : "success" },
    { key: "production", label: t("dealDetail.timeline.production", "Production"), value: t("dealDetail.timeline.pending", "Pending"), tone: "muted" },
    { key: "shipment", label: t("dealDetail.timeline.shipment", "Shipment"), value: t("dealDetail.timeline.pending", "Pending"), tone: "muted" },
    { key: "delivery", label: t("dealDetail.timeline.delivery", "Delivery"), value: t("dealDetail.timeline.pending", "Pending"), tone: "muted" },
  ];
}

export function supplierSaleToDeal(
  sale: Sale,
  t: (k: string, fallback: string) => string,
): DealDetailData {
  const completion = sale.status === "pending_supplier" ? 0 : 0.15;
  return {
    role: "supplier",
    dealNumber: sale.dealId,
    date: sale.orderDate,
    fcls: sale.fclCount,
    totalKg: sale.totalWeightKg,
    product: sale.product,
    totalValueUsd: sale.totalValueUsd,
    status: {
      label: t(`supplier.sales.status.${sale.status}`, sale.status),
      tone: SUPPLIER_STATUS_TONE[sale.status] ?? "info",
    },
    rawStatus: sale.status,
    party: {
      name: sale.buyer,
      country: sale.destination,
      flagEmoji: flag(sale.destination),
    },
    overview: {
      date: sale.orderDate,
      totalValueUsd: sale.totalValueUsd,
      origin: sale.originCountry,
      destination: sale.destination,
      incoterm: sale.incoterm,
      container: `${sale.fclCount}× ${sale.fclSize} FCL`,
      totalVolume: `${new Intl.NumberFormat("de-DE").format(sale.totalWeightKg)} kg`,
      shipmentMonth: sale.shipment,
      species: "Beef",
      temperature: "Frozen · −18°C",
    },
    cuts: sale.cuts.map((c) => ({
      name: c.name,
      weightKg: c.weightKg,
      pricePerKgUsd: c.pricePerKgUsd,
      subItems: c.name.toLowerCase().includes("mixed")
        ? ["Ribeye", "Striploin", "Tenderloin", "Top Sirloin"] : undefined,
    })),
    timeline: supplierTimeline(sale, t),
    negotiation: genNegotiation(sale.dealId, sale.totalValueUsd),
    containers: genShipment(sale.dealId, sale.fclCount, sale.totalWeightKg, sale.originPort, sale.destinationPort),
    journeyStage: statusToJourney("early"),
    documents: genDocuments(sale.dealId, sale.dealId, completion),
    backHref: "/supplier/sales",
    fullNegotiationHref: undefined,
    orderId: sale.id,
    shipmentReadOnly: false,
  };
}
