// Renders a Shipping Instructions document into a hidden iframe and
// triggers the browser print dialog. No new tab, no URL bar — keeps
// the experience clean and never exposes the preview hostname.

type AnyRec = Record<string, unknown>;

function fmtDate(iso: string | null | undefined): string {
  if (!iso) return "—";
  return new Date(iso).toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });
}

function esc(s: unknown): string {
  return String(s ?? "").replace(/[&<>"']/g, (c) =>
    ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]!),
  );
}

function row(k: string, v: unknown): string {
  return `<div class="r"><span class="k">${esc(k)}</span><span class="v">${v ? esc(v) : "—"}</span></div>`;
}

function section(title: string, body: string): string {
  return `<section><h2>${esc(title)}</h2><div>${body}</div></section>`;
}

export function printShippingInstructions(si: AnyRec, request: AnyRec | null): void {
  const docs: string[] = Array.isArray(si.documents_requested) ? (si.documents_requested as string[]) : [];
  const lines: string[] = Array.isArray(si.approved_shipping_lines) ? (si.approved_shipping_lines as string[]) : [];
  const status = String(request?.status ?? "received");
  const statusLabel = status === "approved" ? "Approved" : status === "received" ? "Received" : status;

  const html = `<!doctype html>
<html><head><meta charset="utf-8"/><title>Shipping Instructions</title>
<style>
  *{box-sizing:border-box}
  body{margin:0;font-family:'Inter',system-ui,-apple-system,sans-serif;color:#2a1a20;background:#fff}
  .page{max-width:820px;margin:0 auto;padding:32px 40px}
  header{text-align:center;padding-bottom:16px;border-bottom:3px solid #8B2252;margin-bottom:24px}
  .brand{font-size:13px;font-weight:700;letter-spacing:.2em;color:#8B2252;margin-bottom:6px}
  .title{font-size:24px;font-weight:700;letter-spacing:.04em}
  .meta{display:flex;justify-content:space-between;gap:16px;padding:14px 18px;background:#fdf2f8;border-radius:6px;margin-bottom:24px}
  .meta>div{display:flex;flex-direction:column;gap:2px}
  .meta .lbl{font-size:10px;text-transform:uppercase;letter-spacing:.08em;color:#8B2252;font-weight:700}
  .meta strong{font-size:14px;font-weight:600}
  section{margin-bottom:18px;padding-bottom:14px;border-bottom:1px solid #f1f5f9;page-break-inside:avoid}
  section:last-of-type{border-bottom:none}
  h2{font-size:11px;font-weight:700;letter-spacing:.1em;text-transform:uppercase;color:#8B2252;margin:0 0 8px}
  .r{display:flex;gap:12px;padding:3px 0;font-size:13px}
  .k{color:#6b7280;min-width:110px}
  .v{color:#2a1a20;flex:1}
  p{margin:0;font-size:13px}
  .chips{display:flex;flex-wrap:wrap;gap:6px}
  .chip{background:#fdf2f8;color:#8B2252;padding:4px 10px;border-radius:999px;font-size:12px;font-weight:500}
  footer{margin-top:32px;padding-top:16px;border-top:1px solid #f1f5f9;text-align:center;font-size:11px;color:#9ca3af;line-height:1.6}
  @page{margin:14mm}
</style></head>
<body>
<div class="page">
  <header>
    <div class="brand">MUNDUS TRADE</div>
    <div class="title">SHIPPING INSTRUCTIONS</div>
  </header>
  <div class="meta">
    <div><span class="lbl">Order</span><strong>${esc(si.order_number ?? "—")}</strong></div>
    <div><span class="lbl">Date</span><strong>${esc(fmtDate(request?.submitted_at as string))}</strong></div>
    <div><span class="lbl">Status</span><strong>${esc(statusLabel)}</strong></div>
  </div>
  ${section("Buyer for Invoice", row("Company", si.buyer_name) + row("Address", si.buyer_address))}
  ${section("Destination", row("Port", si.port_of_destination) + row("Country", si.country_of_destination))}
  ${section("Consignee", row("Name", si.consignee_name) + row("Address", si.consignee_address) + row("Phone", si.consignee_phone))}
  ${section("BL Notify Party", row("Name", si.notify_name) + row("Address", si.notify_address) + row("Phone", si.notify_phone))}
  ${section("Documents Requested", `<div class="chips">${docs.length === 0 ? '<span style="color:#9ca3af;font-size:13px">—</span>' : docs.map((d) => `<span class="chip">✓ ${esc(d)}</span>`).join("")}</div>`)}
  ${section("Telex Release", `<p>${esc(si.telex_release ?? "—")}</p>`)}
  ${section("Approved Shipping Lines", `<p>${lines.length ? esc(lines.join(", ")) : "—"}</p>`)}
  ${si.observations ? section("Observations", `<p style="white-space:pre-wrap">${esc(si.observations)}</p>`) : ""}
  <footer>Generated by Mundus Trade · mundustrade.com<br/>This document is for shipping purposes only.</footer>
</div>
<script>setTimeout(function(){try{window.focus();window.print();}catch(e){}},250);</script>
</body></html>`;

  const iframe = document.createElement("iframe");
  iframe.style.position = "fixed";
  iframe.style.right = "0";
  iframe.style.bottom = "0";
  iframe.style.width = "0";
  iframe.style.height = "0";
  iframe.style.border = "0";
  iframe.setAttribute("aria-hidden", "true");
  document.body.appendChild(iframe);

  const cleanup = () => {
    setTimeout(() => {
      try { document.body.removeChild(iframe); } catch { /* noop */ }
    }, 1000);
  };

  const doc = iframe.contentWindow?.document;
  if (!doc) { cleanup(); return; }
  doc.open();
  doc.write(html);
  doc.close();

  const win = iframe.contentWindow;
  if (win) {
    win.addEventListener("afterprint", cleanup);
    // Fallback cleanup if afterprint doesn't fire
    setTimeout(cleanup, 60_000);
  } else {
    cleanup();
  }
}