project_id = "kypyqxicwbusadnlhnwe"

[functions.prospect-phone-webhook]
verify_jwt = false

[functions.verify-email]
verify_jwt = false

[functions.verify-document]
verify_jwt = false

[functions.signup-notifications]
verify_jwt = false