import { AdminDocView, type DocContent, type Lang } from "./AdminDocRenderer";

const CONTENT: Record<Lang, DocContent> = {
  pt: {
    tagline: "Brandbook institucional — referência interna",
    hero: "Identidade, posicionamento, modelo de negócio e diretrizes de comunicação da Mundus Trade.",
    badge: "DOCUMENTO INTERNO | OPERADORES MUNDUS | 2026",
    print: "Imprimir / Salvar PDF",
    footer_kicker: "Mundus Trade",
    footer_lines: [
      "Mundus Trade LLC · Ocoee, Florida, USA",
      "Documento vivo · Versão 2.0",
      "Atualize sempre que houver mudança em estratégia, produto, público ou mensagem",
    ],
    signature: "MUNDUS TRADE | BRANDBOOK INTERNO | 2026",
    sections: [
      {
        kicker: "00 — COMO USAR",
        title: "Como usar este documento",
        blocks: [
          { kind: "lede", text: "Este brandbook tem dois papéis simultâneos: é o documento de referência interna da Mundus Trade e o arquivo que qualquer ferramenta de inteligência artificial deve receber antes de executar qualquer tarefa relacionada à marca." },
          { kind: "table", head: ["Contexto de uso", "O que este documento viabiliza", "Quem usa"], rows: [
            ["Onboarding de novos membros do time", "Qualquer pessoa que entra na Mundus entende em um documento o que a empresa é, para quem serve, como fala e o que não pode fazer.", "Gestão, todo o time"],
            ["Alimentação de IA para criação de posts", "LinkedIn, Instagram, WhatsApp e WeChat. A IA tem contexto completo de persona, tom, canal e objetivos antes de gerar qualquer conteúdo.", "Time de marketing, IA de conteúdo"],
            ["Alimentação de IA para comentários no setor", "Ferramentas que comentam em posts relevantes de terceiros para gerar visibilidade orgânica para a Mundus.", "Time de marketing, IA de engajamento"],
            ["Briefing para agências e freelancers", "Designers, redatores e produtores de vídeo recebem o contexto completo sem precisar de horas de briefing verbal.", "Fernando, Gustavo"],
            ["Alinhamento interno antes de abordagens comerciais", "Qualquer pessoa do time revisa o documento antes de ligar, mandar mensagem ou fazer uma reunião com supplier ou buyer.", "Gustavo, time comercial, Fernando"],
            ["Treinamento contínuo do time", "Base de referência para revisar tom, argumentos e respostas a objeções em qualquer reunião interna.", "Todo o time"],
            ["Geração de e-mails e mensagens B2B", "A IA usa o contexto de persona e tom para redigir abordagens personalizadas para cada perfil de contato.", "Time comercial"],
            ["Criação de materiais de apresentação", "Decks, one-pagers e landing pages partem deste documento como fonte única de verdade sobre a marca.", "Todo o time"],
          ]},
          { kind: "callout", text: "Instrução para IA: antes de executar qualquer tarefa relacionada à Mundus Trade, leia este documento na íntegra. Não assuma nenhuma informação que não esteja aqui. Se precisar de informação ausente, pergunte ao usuário antes de prosseguir." },
        ],
      },
      {
        kicker: "01 — IDENTIDADE",
        title: "O que é a Mundus Trade",
        blocks: [
          { kind: "p", text: "A Mundus Trade é um marketplace B2B global para exportação e importação de proteínas animais. A plataforma conecta frigoríficos (suppliers) de qualquer país do mundo com importadores, traders e compradores (buyers) da China, Oriente Médio, Ásia, Europa, África e Américas." },
          { kind: "p", text: "A Mundus não é uma trading. Não compra nem vende carne. É o canal digital onde frigoríficos publicam ofertas e buyers encontram, negociam e fecham negócio diretamente com o produtor, sem intermediário." },
          { kind: "p", text: "A Mundus é também uma camada de dados em tempo real: ao centralizar negociações globais de proteínas animais, gera inteligência de mercado que nenhum outro serviço do setor oferece com essa velocidade e granularidade." },
          { kind: "h3", text: "Dados cadastrais" },
          { kind: "table", head: ["Campo", "Valor"], rows: [
            ["Razão social", "Mundus Trade LLC"],
            ["Sede", "Ocoee, Florida, USA"],
            ["Fundador", "Fernando Nascimento"],
            ["Lançamento", "17 de novembro de 2024"],
            ["Modelo de receita", "Comissão de 0,30% sobre o valor do negócio fechado. Sem mensalidade. Sem custo de cadastro para nenhum dos lados."],
            ["Custo para o buyer", "Gratuito. O buyer nunca paga nada para usar a plataforma."],
          ]},
          { kind: "h3", text: "Missão" },
          { kind: "p", text: "Digitalizar e democratizar o comércio internacional de proteínas animais, conectando diretamente frigoríficos e compradores do mundo inteiro com transparência, velocidade e inteligência de mercado em tempo real." },
          { kind: "h3", text: "Visão" },
          { kind: "p", text: "Ser a principal plataforma global de negociação de proteínas animais e a referência de inteligência de mercado do setor, tornando o comércio B2B tão simples, rápido e transparente quanto qualquer marketplace moderno." },
          { kind: "h3", text: "Valores" },
          { kind: "ul", items: [
            "Transparência: preço, histórico e dados de mercado visíveis para quem está dentro da plataforma.",
            "Eficiência: o que hoje leva dias de e-mail deve acontecer em minutos.",
            "Confiança: fornecedores verificados, sem surpresa de qualidade ou documentação.",
            "Neutralidade: a Mundus não toma partido. Facilita o negócio sem substituir a relação comercial.",
            "Alcance global: suppliers e buyers de qualquer país são bem-vindos.",
            "Inteligência de mercado: dados reais, em tempo real, para decisões melhores dos dois lados.",
          ]},
          { kind: "callout", text: "Posicionamento em uma frase: o lugar onde frigoríficos do mundo inteiro encontram compradores globais, negociam e fecham com velocidade e transparência, sem intermediário, e onde o mercado de proteínas animais passa a ter dados em tempo real pela primeira vez." },
          { kind: "h3", text: "A história por trás da Mundus" },
          { kind: "p", text: "Fernando Nascimento tem mais de 28 anos de carreira no comércio internacional de carnes. Começou como office boy no Minerva Foods, em Barretos (SP), foi crescendo na área de exportação e mora nos Estados Unidos coordenando operações de trading global pela WMS Foods, empresa que fundou." },
          { kind: "p", text: "A WMS Foods opera há anos como trading intermediária no mercado de exportação de carnes, com contato direto com mais de 2.500 compradores globais em China, Oriente Médio, Europa e Américas e histórico comprovado de fechamento de negócios internacionais. Esse network e essa credibilidade são a base sobre a qual a Mundus foi construída." },
          { kind: "p", text: "A observação que gerou a Mundus foi direta: em 2024, frigoríficos e importadores do mundo inteiro ainda negociavam por e-mail, WhatsApp, WeChat e ligações. Para colocar uma oferta no mercado, um trader mandava 200 a 300 e-mails por dia. Para comprar, um importador esperava dias por cotação e ainda corria o risco de perder a janela de preço. A Mundus nasceu para eliminar esse atrito, criada por quem viveu o problema por quase três décadas." },
        ],
      },
      {
        kicker: "02 — COMO FUNCIONA",
        title: "O modelo de marketplace",
        blocks: [
          { kind: "p", text: "A Mundus opera no modelo de two-sided marketplace: suppliers publicam ofertas e buyers publicam demanda. O sistema cruza esses dados e facilita a negociação diretamente entre as partes, sem que ninguém precise sair da plataforma para fechar o negócio." },
          { kind: "table", head: ["Etapa", "Supplier", "Buyer"], rows: [
            ["Cadastro", "Registra operações, proteínas, volumes, mercados habilitados e documentação sanitária. Pode ser feito pelo frigorífico ou via equipe comercial da Mundus.", "Registra empresa, mercados de interesse e produtos que demanda."],
            ["Publicação", "Posta ofertas com specs técnicas, preço pedido, incoterm, porto de embarque e número do SIF.", "Posta demandas abertas: o que quer comprar, volume e especificação técnica."],
            ["Negociação", "Responde bids, recebe propostas e negocia dentro da plataforma, com histórico registrado.", "Envia bids, responde ofertas e negocia direto com o frigorífico."],
            ["Fechamento", "Conclui o negócio. Comissão de 0,30% sobre o valor fechado.", "Acesso gratuito. O buyer não paga nada."],
          ]},
          { kind: "h3", text: "O modelo atual" },
          { kind: "p", text: "Antes da Mundus, o fluxo de uma negociação internacional de carne funcionava assim: o trader mandava 200 a 300 e-mails por dia para colocar uma oferta no mercado; o buyer esperava dias por uma cotação, muitas vezes sem resposta; quando estava perto de fechar, a oferta já não estava disponível; não havia transparência de preço; e o histórico ficava disperso em inboxes pessoais e conversas de WhatsApp." },
          { kind: "p", text: "Com a Mundus: o supplier posta uma oferta e todos os buyers habilitados a veem simultaneamente; o buyer compara ofertas padronizadas sem precisar pedir cotação; a negociação acontece em minutos dentro dos parâmetros pré-definidos pelo frigorífico; ambos os lados têm visibilidade de preço, volume e demanda do mercado global em tempo real; e o histórico de negociações fica centralizado e acessível." },
          { kind: "h3", text: "Futuro: inteligência de mercado como produto" },
          { kind: "p", text: "Quando a Mundus acumular volume de transações, passará a ter algo que nenhum outro serviço do setor tem hoje: dados de preços e volumes negociados em tempo real, por proteína, corte, mercado e origem." },
          { kind: "p", text: "Hoje a Datamar vende dados de exportações brasileiras com 20 a 30 dias de atraso, extraídos do Banco Central. Associações como ABIEC (bovina) e BPA (suína) publicam dados com lag de 30 a 60 dias. A Mundus, com transações acontecendo na plataforma, terá esses dados ao vivo. Isso representa uma fonte adicional de receita no médio prazo e uma alavanca de parceria com associações setoriais, que recebem dados em tempo real em troca de distribuição e credibilidade institucional." },
          { kind: "h3", text: "O que a Mundus NÃO é" },
          { kind: "ul", items: [
            "Não é uma trading: não compra nem vende carne em nenhum momento.",
            "Não é um broker: não representa nenhuma das partes na negociação.",
            "Não é restrita ao Brasil: suppliers vêm de qualquer país do mundo.",
            "Não é um ERP ou sistema de gestão para frigoríficos.",
            "Não cobra mensalidade: o modelo é 100% baseado em resultado.",
          ]},
          { kind: "callout", text: "Atenção: nunca assuma que os suppliers da Mundus são só brasileiros. A plataforma é global. Frigoríficos da Argentina, Uruguai, Austrália, Europa Oriental, Índia, Ucrânia e qualquer outro país exportador são público da Mundus." },
        ],
      },
      {
        kicker: "03 — PÚBLICO-ALVO",
        title: "Personas de Suppliers e Buyers",
        blocks: [
          { kind: "p", text: "Lado supplier: frigoríficos de qualquer origem que exportam ou querem exportar proteínas animais (bovina, suína, frango, ovina e outras). Lado buyer: importadores, distribuidores e traders de compra. Base de contatos disponível: cerca de 2.500 contatos ativos da WMS Foods, com histórico de relacionamento direto com Fernando e o time." },
          { kind: "h3", text: "S1 — Dono ou Diretor do Frigorífico" },
          { kind: "p", text: "CEO ou dono da operação. Toma decisões estratégicas. Quer maximizar preço de venda, diversificar mercados, reduzir dependência de um ou dois traders e ter visibilidade do que o time de exportação faz. Teme perder controle e expor preço para concorrentes. Como falar: resultado financeiro, não funcionalidade." },
          { kind: "h3", text: "S2 — Gerente de Exportação" },
          { kind: "p", text: "Responsável técnico. Conhece cada mercado, incoterm e habilitação sanitária. Quer eficiência operacional e clareza sobre o que o mercado paga agora. Teme mais uma ferramenta que gere mais trabalho. Como falar: demonstração prática, caso de uso real. Tempo é o argumento central." },
          { kind: "h3", text: "S3 — Trader do Frigorífico" },
          { kind: "p", text: "Executa as negociações do dia a dia. Frequentemente o ponto de resistência. Teme ser substituído. Como quebrar: a Mundus não substitui o trader, amplifica o alcance dele. Ele continua sendo quem fecha. Sinal de alerta: quando o trader já tem interesse e pula direto para o operacional (pede demo, quer subir oferta), não force o roteiro de entrevista, aproveite como oportunidade de ativação imediata." },
          { kind: "h3", text: "B1 — Dono ou Diretor do Importador" },
          { kind: "p", text: "Decide sobre fornecedores estratégicos. Quer diversificar origem, garantir qualidade e ter previsibilidade de preço e volume. Teme surpresa de qualidade e fornecedor sem habilitação para o seu mercado. Custo na Mundus: zero." },
          { kind: "h3", text: "B2 — Comprador Operacional" },
          { kind: "p", text: "Executa as compras do dia a dia. Quer velocidade. Frase real de entrevista: \"Traders não respondem a tempo. Quando respondem, a oferta já fechou.\" Como falar: velocidade e disponibilidade de oferta, não preço." },
        ],
      },
      {
        kicker: "04 — DORES RESOLVIDAS",
        title: "O que a Mundus resolve",
        blocks: [
          { kind: "h3", text: "Para Suppliers" },
          { kind: "table", head: ["Palavra-chave", "O que resolve", "Ganho na prática"], rows: [
            ["Inteligência", "Visibilidade de demanda e preços em tempo real, por mercado e proteína.", "Sabe o que o mercado paga antes de fechar. Para de deixar dinheiro na mesa."],
            ["Alcance", "Acesso a compradores verificados globalmente, além do network atual.", "Chega em Filipinas, Indonésia e Oriente Médio sem passagem de feira."],
            ["Controle", "Histórico centralizado: o que foi negociado, por quem e a qual preço.", "Vê o que o time faz sem perguntar. Decide com dados."],
            ["Resiliência", "Visibilidade antecipada de demanda em mercados alternativos.", "Quando a cota da China fecha, já sabe para onde mover."],
            ["Risco zero", "Sem mensalidade. Paga 0,30% só quando o negócio fecha.", "Experimenta sem comprometer orçamento."],
          ]},
          { kind: "h3", text: "Para Buyers" },
          { kind: "table", head: ["Palavra-chave", "O que resolve", "Ganho na prática"], rows: [
            ["Transparência", "Ofertas padronizadas: produto, preço, incoterm, porto e specs.", "Bate o olho e compara. Sem pedir cotação, sem planilha manual."],
            ["Confiança", "Só frigoríficos verificados. Sem intermediário invisível.", "Negocia direto com o produtor. Vê SIF, número da fábrica e histórico."],
            ["Velocidade", "Negociação dentro dos parâmetros pré-definidos.", "O que leva 3 dias de e-mail acontece em 10 minutos."],
            ["Demanda ativa", "Pode publicar o que quer comprar. Os frigoríficos vêm até ele.", "Inverte a lógica: posta o que precisa e o mercado responde."],
            ["Custo zero", "Acesso gratuito, sem assinatura.", "Nenhum risco para experimentar."],
          ]},
        ],
      },
      {
        kicker: "05 — OBJEÇÕES",
        title: "Objeções comuns e como responder",
        blocks: [
          { kind: "h3", text: "Suppliers" },
          { kind: "table", head: ["Objeção", "Como responder"], rows: [
            ["\"Já tenho mais clientes do que consigo atender.\"", "Então você pode escolher quem paga mais. Mas só consegue se tiver acesso a todas as opções. Hoje vende para quem conhece, não para quem paga melhor agora."],
            ["\"Não tenho tempo. Meu time está sobrecarregado.\"", "Você não opera, seu trader opera. A Mundus tira trabalho do time, não adiciona. E você passa a ter visibilidade sem entrar em cada conversa."],
            ["\"Prefiro esperar estar mais estável.\"", "Por isso o modelo é sem mensalidade. Só paga quando fechar. Risco zero. O risco de esperar enquanto o concorrente já está dentro é outro assunto."],
            ["\"Não tenho buyer para minha proteína específica.\"", "Essa é exatamente a informação que a Mundus tem: o que está sendo demandado, em qual mercado e a que preço. Vale ver o que está ativo agora."],
            ["\"Não vou colocar meus clientes lá.\"", "A plataforma não expõe seu cliente para concorrente. Você vê demandas de mercado, não o contato do seu buyer."],
            ["\"Já mando muito e-mail e funciona.\"", "Funciona porque é o único jeito que existe. Quando o comprador tiver opção de ver todas as ofertas em um lugar sem esperar seu e-mail, o que muda para você?"],
            ["\"Nunca ouvi falar da Mundus. Por que confiar?\"", "A Mundus foi criada por Fernando Nascimento, que opera no comércio internacional de carnes há mais de 28 anos pela WMS Foods. A plataforma nasce com a credibilidade de quem já fechou negócios com compradores em China, Oriente Médio, Europa e Américas."],
          ]},
          { kind: "h3", text: "Buyers" },
          { kind: "table", head: ["Objeção", "Como responder"], rows: [
            ["\"A plataforma está vazia. Não tem oferta suficiente.\"", "Você pode postar o que precisa comprar agora. Os frigoríficos veem essa demanda e respondem com oferta direcionada. Não precisa esperar a plataforma encher."],
            ["\"Já tenho meus fornecedores fixos.\"", "Não significa trocar. Significa ter opções quando o seu não consegue atender ou o preço está fora. É um seguro de fornecimento, de graça."],
            ["\"Prefiro negociar por e-mail.\"", "Por e-mail espera dias. Aqui tem resposta em minutos. E a oferta não desaparece porque o trader estava ocupado."],
            ["\"Como sei que os frigoríficos são verificados?\"", "Cada supplier passa por verificação documental antes de publicar. Você vê o SIF, o número da fábrica e o histórico registrado. Além disso, a plataforma foi criada por Fernando Nascimento, que opera no setor há mais de 28 anos pela WMS Foods."],
            ["\"Já trabalho com a WMS Foods. Para que usar outra plataforma?\"", "A Mundus é a evolução natural desse relacionamento: mesma credibilidade, mais transparência, mais opções e mais velocidade. E você acessa tudo de graça."],
          ]},
        ],
      },
      {
        kicker: "06 — TOM DE VOZ",
        title: "Personalidade e linguagem da marca",
        blocks: [
          { kind: "p", text: "A Mundus fala com profissionais que passaram a vida inteira no comércio internacional de carnes. Não são iniciantes. São pessoas com 10, 20, 30 anos de mercado, com relacionamentos consolidados e ceticismo saudável em relação a novidades tecnológicas. A Mundus não tenta parecer uma startup de tecnologia: é uma plataforma construída por quem conhece o setor por dentro." },
          { kind: "table", head: ["Fala assim", "Nunca fala assim"], rows: [
            ["Direto, sem rodeio", "Marketing vago e clichê"],
            ["Números e dados quando existem", "\"Somos líderes em inovação\""],
            ["Vocabulário do setor: SIF, incoterm, bid, DDP, FOB", "Linguagem genérica de tecnologia"],
            ["Respeita a inteligência do interlocutor", "Tom condescendente ou pedagógico"],
            ["Provoca o status quo: por que você ainda faz assim?", "Pressão direta ou vendedor de feira"],
            ["Inclui o buyer como protagonista, não como usuário", "Foco só em funcionalidade da plataforma"],
            ["Fala sobre o momento do mercado: quem entra agora tem vantagem", "\"Junte-se a nós hoje\" sem contexto real"],
            ["Específico e contextualizado para o setor", "Conteúdo que poderia ser de qualquer empresa"],
          ]},
          { kind: "h3", text: "Frases que representam a marca" },
          { kind: "ul", items: [
            "\"Você manda 300 e-mails por dia para colocar uma oferta. A Mundus manda para todos de uma vez.\"",
            "\"O que hoje leva 3 dias de e-mail acontece em 10 minutos.\"",
            "\"Quando a cota da China fecha, quem já está na Mundus já sabe para onde mover.\"",
            "\"Negocia direto com o frigorífico. Sem intermediário. Sem surpresa de preço.\"",
            "\"0,30% só quando o negócio fecha. Se não fechar, não custou nada.\"",
            "\"Você posta o que precisa comprar. Os frigoríficos vêm até você.\"",
          ]},
          { kind: "h3", text: "O que nunca fazer ao falar pela Mundus" },
          { kind: "ul", items: [
            "Usar vocabulário de startup: 'disrupção', 'ecossistema', 'jornada do usuário', 'sinergia'.",
            "Prometer resultados não comprovados.",
            "Usar travessão (---) no lugar de pontuação. Parece conteúdo de máquina.",
            "Emoji em excesso em LinkedIn e e-mail B2B.",
            "Assumir que o interlocutor é brasileiro. A Mundus é global.",
            "Generalizar suppliers como 'frigoríficos brasileiros'.",
            "Citar funcionalidade técnica como argumento principal. O argumento é sempre o resultado para o cliente.",
            "Posicionar a Mundus como trading ou intermediária. A Mundus é neutra e facilita a negociação direta entre as partes.",
          ]},
        ],
      },
      {
        kicker: "07 — CANAIS",
        title: "Presença digital e estratégia por canal",
        blocks: [
          { kind: "p", text: "A Mundus é pioneira num segmento que ainda não foi digitalizado. O mercado não busca ativamente uma solução como ela. O conteúdo precisa criar o problema na cabeça do público antes de apresentar a solução." },
          { kind: "callout", text: "Sequência ideal: (1) mostrar a dor do jeito atual; (2) provocar com pergunta ou dado; (3) apresentar a Mundus como saída natural, sem forçar." },
          { kind: "table", head: ["Canal", "Público prioritário", "Tom e objetivo"], rows: [
            ["LinkedIn", "Frigoríficos e importadores da Europa e Américas. B2B em geral.", "Educação e credibilidade. Posts analíticos. Terminar com pergunta. Foco em inglês com conteúdo em português."],
            ["Instagram", "Oriente Médio, público jovem do setor.", "Visual, bastidores, presença em feiras. Reels com dado de mercado. Identidade em vinho e cinza escuro."],
            ["WhatsApp", "Oriente Médio e contatos individuais para negócio.", "Mensagens curtas e diretas. Nunca conteúdo de massa."],
            ["WeChat", "China.", "Canal específico para compradores chineses. Linguagem adaptada."],
            ["YouTube", "Fase futura, com casos comprovados.", "Demonstrações, depoimentos e tutoriais."],
          ]},
          { kind: "h3", text: "Diagnóstico de presença atual (referência 2025/2026)" },
          { kind: "table", head: ["Canal", "Status"], rows: [
            ["LinkedIn", "Cerca de 900 seguidores. Boa qualidade de copy. Falta regularidade, dados concretos e narrativa sequencial entre posts."],
            ["Instagram", "Cerca de 189 seguidores. Identidade visual consistente em vinho e bordô. Zero Reels. Frequência baixa. Sem estratégia de hashtags."],
            ["Fase atual", "Awareness e educação. O mercado ainda não entende o que é a Mundus. A função da comunicação agora é criar consciência de problema antes de apresentar solução."],
          ]},
          { kind: "h3", text: "Regra de ouro: externo vs. interno" },
          { kind: "table", head: ["Conteúdo externo (público)", "Conteúdo interno (só logados)"], rows: [
            ["Vídeo institucional: gera curiosidade, não mostra funcionalidades", "Vídeos passo a passo da plataforma"],
            ["Posts de mercado e dados setoriais", "Help Center e tutoriais de uso"],
            ["Narrativa de credibilidade e posicionamento", "Demos completas de produto"],
          ]},
        ],
      },
      {
        kicker: "08 — MERCADOS",
        title: "Mercados e geografias",
        blocks: [
          { kind: "p", text: "A Mundus é marketplace global sem restrição geográfica. Frigoríficos de qualquer país podem se cadastrar. Buyers de qualquer região podem comprar." },
          { kind: "h3", text: "Mercados de buyers" },
          { kind: "ul", items: [
            "China: maior importador de carnes do mundo. WeChat como canal B2B.",
            "Oriente Médio: Arábia Saudita, EAU, Paquistão. WhatsApp e Instagram.",
            "Ásia: Filipinas, Indonésia, Japão, Coreia do Sul.",
            "Europa: importadores e distribuidores. LinkedIn e e-mail.",
            "Américas: EUA, Caribe, América Latina.",
            "África: mercados em crescimento para proteínas mais acessíveis.",
          ]},
          { kind: "h3", text: "Mercados de suppliers" },
          { kind: "p", text: "Network inicial concentrado no Brasil, mas aberto para frigoríficos da Argentina, Uruguai, Austrália, Nova Zelândia, Europa Oriental, Índia, Ucrânia e qualquer outro país exportador." },
          { kind: "callout", text: "IMPORTANTE: nunca assumir que supplier equivale a frigorífico brasileiro. A Mundus é global. Correção não negociável em qualquer conteúdo gerado." },
        ],
      },
      {
        kicker: "09 — COMPETIÇÃO",
        title: "Contexto competitivo",
        blocks: [
          { kind: "p", text: "A Mundus não tem concorrente direto em 2026. Não existe outra plataforma global que conecte frigoríficos e importadores no modelo de marketplace B2B com negociação dentro da plataforma. Quem chegar primeiro e construir densidade define o padrão do setor." },
          { kind: "table", head: ["Serviço/empresa", "Por que não é o mesmo"], rows: [
            ["E-mail e WhatsApp", "Método atual do mercado. Não é plataforma. A Mundus substitui esse fluxo."],
            ["Feiras (Gulfood, SIAL)", "Relacionamento presencial. A Mundus complementa, não substitui."],
            ["Datamar", "Vende dados com 20-30 dias de atraso. Não é marketplace, não conecta partes."],
            ["Trade Cafe", "Trading com plataforma própria, não marketplace neutro."],
            ["Plataformas agrícolas genéricas", "Não são especializadas em proteínas. Falta vocabulário e fluxos do setor."],
          ]},
        ],
      },
      {
        kicker: "10 — TIME",
        title: "Time Mundus",
        blocks: [
          { kind: "table", head: ["Membro", "Papel"], rows: [
            ["Fernando Nascimento", "Fundador e CEO. Mais de 28 anos no comércio internacional de carnes (Minerva Foods, WMS Foods). Baseado em Miami. Face pública da Mundus. Network com mais de 100 frigoríficos e mais de 2.500 contatos de buyers globais."],
            ["Débora", "Sócia. Finanças e administração. Perfil analítico. Cogestora da WMS Foods."],
            ["Gustavo Cândido", "Comercial e operacional. Co-executor das ações de ativação. Interface com frigoríficos e buyers no dia a dia."],
            ["Jennifer", "Operacional WMS Foods. Suporte à execução do modelo de ativação: organização e upload de ofertas na plataforma."],
            ["Alexandre", "Sócio com foco em TI. Acompanha o desenvolvimento técnico da plataforma."],
          ]},
        ],
      },
      {
        kicker: "11 — REGRAS PARA IA",
        title: "Obrigatório ler antes de executar",
        blocks: [
          { kind: "h3", text: "Confirmar antes de gerar qualquer conteúdo" },
          { kind: "ul", items: [
            "Para qual persona? (Dono de frigorífico, gerente de exportação, trader, buyer?)",
            "Em qual canal? (LinkedIn, Instagram, WhatsApp, e-mail?)",
            "Qual o objetivo? (Awareness, cadastro, ativação de oferta, ativação de demanda, onboarding?)",
            "Em qual idioma? (Português, inglês, espanhol, árabe?)",
            "Para supplier, buyer ou os dois?",
          ]},
          { kind: "h3", text: "Regras inegociáveis" },
          { kind: "ul", items: [
            "A Mundus é global. Suppliers não são exclusivamente brasileiros.",
            "A Mundus não é uma trading. Não compra nem vende carne.",
            "O buyer nunca paga nada. A comissão de 0,30% é exclusiva do supplier.",
            "Nunca usar travessão. Usar vírgula, ponto ou dois-pontos.",
            "Nunca gerar conteúdo genérico. Se serve para qualquer empresa, não serve.",
            "Nunca citar funcionalidade técnica como argumento central. O argumento é o resultado para o cliente.",
            "Nunca prometer resultado não comprovado.",
            "Nunca posicionar a Mundus como intermediária. Ela é neutra e facilita a negociação direta entre as partes.",
          ]},
          { kind: "h3", text: "Frases proibidas" },
          { kind: "ul", items: [
            "\"Solução inovadora para o seu negócio.\"",
            "\"Transforme sua operação.\"",
            "\"Somos líderes em disrupção.\"",
            "\"Clique aqui para saber mais.\"",
            "Qualquer frase que poderia ser publicada por uma empresa de qualquer outro setor.",
          ]},
        ],
      },
      {
        kicker: "12 — GLOSSÁRIO",
        title: "Glossário do setor",
        blocks: [
          { kind: "table", head: ["Termo", "Significado no contexto Mundus"], rows: [
            ["Supplier", "Frigorífico que vende e exporta. Publica ofertas. Paga 0,30% ao fechar."],
            ["Buyer", "Importador ou trader de compra. Busca ofertas ou publica demanda. Acesso gratuito."],
            ["SIF", "Serviço de Inspeção Federal (Brasil). Certifica o frigorífico para exportação. Existe equivalente em outros países."],
            ["Incoterm", "Termos internacionais de comércio. Definem quem paga frete e até qual ponto. Ex.: FOB, CIF, DDP."],
            ["FOB", "Free on Board: vendedor entrega no porto de origem. Comprador paga frete internacional."],
            ["CIF", "Cost, Insurance and Freight: vendedor paga frete e seguro até o porto de destino."],
            ["DDP", "Delivered Duty Paid: vendedor entrega no destino final, incluindo impostos."],
            ["Container", "Unidade de carga refrigerada. Tipicamente 20 a 27 toneladas."],
            ["Bid", "Proposta de compra do buyer em resposta a uma oferta."],
            ["Habilitação sanitária", "Autorização do país importador para o frigorífico exportar."],
            ["Cota", "Limite de importação por origem. Ex.: cota da China para carne brasileira."],
            ["Trading", "Empresa intermediária. A Mundus NÃO é uma trading."],
            ["Proteína", "Categoria de produto. Bovina, suína, frango, ovina, peixes."],
            ["Corte", "Parte específica do animal. Contrafilé, fraldinha, paleta, picanha."],
            ["Frigorífico / Meatpacker", "Empresa que processa e empacota carnes para exportação."],
            ["WMS Foods", "Trading do Fernando Nascimento. Origem do network e âncora de credibilidade da Mundus."],
            ["Gulfood", "Maior feira de alimentos do mundo (Dubai). Relevante para Oriente Médio."],
            ["SIAL", "Feira internacional de alimentos (Paris). Relevante para Europa."],
            ["Chemical Lean (CL)", "Percentual de gordura da carne. Relevante para EUA e Europa."],
            ["Datamar", "Vende dados de exportação brasileiros com 20-30 dias de atraso. A Mundus supera com dados em tempo real."],
            ["Mundus Beef Index", "Produto futuro da Mundus: índice de preços e volumes negociados em tempo real, por proteína, corte, mercado e origem. Sem equivalente no setor hoje."],
          ]},
        ],
      },
      {
        kicker: "13 — MANUTENÇÃO",
        title: "Como manter este documento atualizado",
        blocks: [
          { kind: "p", text: "Este é um documento vivo. Deve ser revisado sempre que houver mudança relevante. A responsabilidade de atualizar é de quem lidera cada área. A versão mais recente deve ser a única em circulação." },
          { kind: "table", head: ["O que mudou", "Seções a revisar", "Quem atualiza"], rows: [
            ["Nova funcionalidade na plataforma", "Como funciona, Dores resolvidas", "Fernando ou produto"],
            ["Novo mercado geográfico", "Público, Mercados", "Fernando ou Gustavo"],
            ["Mudança no modelo de comissão ou preço", "Como funciona, Dores, Regras para IA", "Fernando"],
            ["Novo membro no time", "Time", "Gestão"],
            ["Novo aprendizado sobre persona", "Público, Objeções, Tom de voz", "Quem conduziu a entrevista"],
            ["Surgimento de concorrente", "Contexto competitivo", "Fernando"],
            ["Caso de sucesso comprovado", "Dores resolvidas, Objeções (prova social)", "Gustavo ou Fernando"],
            ["Mudança de estratégia de canal", "Canais digitais", "Marketing"],
          ]},
          { kind: "h3", text: "Histórico de versões" },
          { kind: "table", head: ["Versão", "Data e principais alterações"], rows: [
            ["v1.0", "Abril 2026. Versão inicial: identidade, personas, benefícios, tom de voz, canais, mercados, competitivo, time, regras para IA e glossário."],
            ["v1.1", "Maio 2026. Reposicionamento como camada de dados em tempo real (Mundus Beef Index). Credenciais WMS Foods como âncora de confiança. Atualização do time. Novas objeções e regra de posicionamento neutro. Regra de conteúdo externo vs. interno. Expansão do glossário."],
            ["v2.0", "2026. Consolidação no admin docs da plataforma. História WMS expandida (2.500 buyers), bloco de futuro (Mundus Beef Index), diagnóstico de presença, seção de manutenção e atualização do time (Jennifer)."],
          ]},
        ],
      },
    ],
  },

  en: {
    tagline: "Institutional brandbook — internal reference",
    hero: "Identity, positioning, business model and communication guidelines of Mundus Trade.",
    badge: "INTERNAL DOCUMENT | MUNDUS OPERATORS | 2026",
    print: "Print / Save PDF",
    footer_kicker: "Mundus Trade",
    footer_lines: [
      "Mundus Trade LLC · Ocoee, Florida, USA",
      "Living document · Version 2.0",
      "Update whenever strategy, product, audience or message changes",
    ],
    signature: "MUNDUS TRADE | INTERNAL BRANDBOOK | 2026",
    sections: [
      {
        kicker: "00 — HOW TO USE",
        title: "How to use this document",
        blocks: [
          { kind: "lede", text: "This brandbook serves two roles at once: it is the internal reference document of Mundus Trade and the file any AI tool should receive before executing any brand-related task." },
          { kind: "table", head: ["Use context", "What it enables", "Who uses it"], rows: [
            ["Onboarding new team members", "Anyone joining Mundus understands in a single document what the company is, who it serves, how it speaks and what it must not do.", "Management, whole team"],
            ["AI for content creation", "LinkedIn, Instagram, WhatsApp and WeChat. The AI has full context of persona, tone, channel and goals before generating anything.", "Marketing, content AI"],
            ["AI for industry comments", "Tools that comment on relevant third-party posts to generate organic visibility for Mundus.", "Marketing, engagement AI"],
            ["Briefing agencies and freelancers", "Designers, copywriters and producers get full context without hours of verbal briefing.", "Fernando, Gustavo"],
            ["Commercial alignment", "Anyone reviews the document before calling, messaging or meeting with a supplier or buyer.", "Gustavo, commercial team, Fernando"],
            ["Continuous team training", "Reference base to review tone, arguments and objection responses in any internal meeting.", "Whole team"],
            ["B2B email generation", "The AI uses persona and tone context to write personalised outreach per contact profile.", "Commercial team"],
            ["Presentation materials", "Decks, one-pagers and landing pages start from this document as the single source of truth.", "Whole team"],
          ]},
          { kind: "callout", text: "Instruction for AI: before executing any Mundus Trade task, read this document in full. Do not assume any information that isn't here. If you need missing information, ask the user first." },
        ],
      },
      {
        kicker: "01 — IDENTITY",
        title: "What Mundus Trade is",
        blocks: [
          { kind: "p", text: "Mundus Trade is a global B2B marketplace for the export and import of animal proteins. It connects meatpackers (suppliers) from any country in the world with importers, traders and buyers in China, the Middle East, Asia, Europe, Africa and the Americas." },
          { kind: "p", text: "Mundus is not a trading. It does not buy or sell meat. It is the digital channel where meatpackers publish offers and buyers find, negotiate and close deals directly with the producer, with no middleman." },
          { kind: "p", text: "Mundus is also a real-time data layer: by centralising global animal-protein negotiations, it generates market intelligence no other service in the sector offers at this speed and granularity." },
          { kind: "h3", text: "Company data" },
          { kind: "table", head: ["Field", "Value"], rows: [
            ["Legal name", "Mundus Trade LLC"],
            ["Headquarters", "Ocoee, Florida, USA"],
            ["Founder", "Fernando Nascimento"],
            ["Platform launch", "November 17, 2024"],
            ["Revenue model", "0.30% commission on closed deal value. No monthly fee. No registration cost for either side."],
            ["Cost for the buyer", "Free. The buyer never pays anything to use the platform."],
          ]},
          { kind: "h3", text: "Mission" },
          { kind: "p", text: "Digitise and democratise the international trade of animal proteins, directly connecting meatpackers and buyers worldwide with transparency, speed and real-time market intelligence." },
          { kind: "h3", text: "Vision" },
          { kind: "p", text: "To be the leading global platform for animal-protein trade and the market-intelligence reference of the sector, making B2B commerce as simple, fast and transparent as any modern marketplace." },
          { kind: "h3", text: "Values" },
          { kind: "ul", items: [
            "Transparency: price, history and market data visible to platform users.",
            "Efficiency: what today takes days of email should happen in minutes.",
            "Trust: verified suppliers, no surprises in quality or documentation.",
            "Neutrality: Mundus does not take sides. It facilitates the deal without replacing the commercial relationship.",
            "Global reach: suppliers and buyers from any country are welcome.",
            "Market intelligence: real, real-time data for better decisions on both sides.",
          ]},
          { kind: "callout", text: "Positioning in one sentence: the place where meatpackers from around the world find global buyers, negotiate and close with speed and transparency, no middleman, and where the animal-protein market gets real-time data for the first time." },
          { kind: "h3", text: "The story behind Mundus" },
          { kind: "p", text: "Fernando Nascimento has over 28 years of experience in international meat trade. He started as office boy at Minerva Foods in Barretos (SP), grew within the export area and now lives in the US coordinating global trading operations through WMS Foods, the company he founded." },
          { kind: "p", text: "WMS Foods has operated for years as an intermediary trading company in meat export, with direct contact with over 2,500 global buyers in China, the Middle East, Europe and the Americas and a proven track record of closing international deals. That network and credibility are the base Mundus was built on." },
          { kind: "p", text: "The observation that gave birth to Mundus was direct: in 2024, meatpackers and importers worldwide still negotiated by email, WhatsApp, WeChat and calls. To put an offer on the market, a trader sent 200 to 300 emails a day. To buy, an importer waited days for a quote and risked losing the price window. Mundus was born to eliminate that friction, built by someone who lived the problem for nearly three decades." },
        ],
      },
      {
        kicker: "02 — HOW IT WORKS",
        title: "The marketplace model",
        blocks: [
          { kind: "p", text: "Mundus operates as a two-sided marketplace: suppliers publish offers and buyers publish demand. The system cross-references that data and facilitates negotiation directly between the parties, without anyone leaving the platform to close." },
          { kind: "table", head: ["Step", "Supplier", "Buyer"], rows: [
            ["Registration", "Registers operations, proteins, volumes, eligible markets and sanitary documentation. Can be done by the packer or via the Mundus commercial team.", "Registers company, target markets and products in demand."],
            ["Publication", "Posts offers with technical specs, asking price, incoterm, shipping port and SIF number.", "Posts open demands: what to buy, volume and specs."],
            ["Negotiation", "Replies to bids and receives proposals on the platform, with full history.", "Sends bids, replies to offers and negotiates directly with the packer."],
            ["Closing", "Closes the deal. 0.30% commission applies on closed value.", "Free access. The buyer pays nothing."],
          ]},
          { kind: "h3", text: "The current model" },
          { kind: "p", text: "Before Mundus, an international meat negotiation worked like this: the trader sent 200 to 300 emails a day to place an offer; the buyer waited days for a quote, often without reply; when close to closing, the offer was no longer available; there was no price transparency; and history was scattered across personal inboxes and WhatsApp chats." },
          { kind: "p", text: "With Mundus: the supplier posts an offer and all eligible buyers see it simultaneously; the buyer compares standardised offers without requesting quotes; negotiation happens in minutes within the packer's pre-defined parameters; both sides have real-time visibility of global price, volume and demand; and negotiation history is centralised and accessible." },
          { kind: "h3", text: "Future: market intelligence as a product" },
          { kind: "p", text: "Once Mundus accumulates transaction volume, it will have something no other service in the sector has today: real-time negotiated price and volume data, by protein, cut, market and origin." },
          { kind: "p", text: "Today Datamar sells Brazilian export data with a 20 to 30 day delay, pulled from the Central Bank. Associations such as ABIEC (beef) and BPA (pork) publish data with a 30 to 60 day lag. Mundus, with transactions happening on the platform, will have this data live. That means an additional medium-term revenue stream and a partnership lever with industry associations." },
          { kind: "h3", text: "What Mundus is NOT" },
          { kind: "ul", items: [
            "Not a trading: never buys or sells meat.",
            "Not a broker: doesn't represent either party.",
            "Not Brazil-restricted: suppliers come from any country.",
            "Not an ERP or management system for packers.",
            "No monthly fee: 100% performance-based.",
          ]},
          { kind: "callout", text: "Never assume Mundus suppliers are only Brazilian. The platform is global. Meatpackers from Argentina, Uruguay, Australia, Eastern Europe, India, Ukraine and any other exporting country are equally part of the audience." },
        ],
      },
      {
        kicker: "03 — AUDIENCE",
        title: "Supplier and buyer personas",
        blocks: [
          { kind: "p", text: "Supplier side: meatpackers of any origin that export or want to export animal proteins (beef, pork, poultry, lamb and others). Buyer side: importers, distributors and purchase traders. Available contact base: around 2,500 active WMS Foods contacts with direct relationship history with Fernando and the team." },
          { kind: "h3", text: "S1 — Meatpacker Owner or Director" },
          { kind: "p", text: "CEO or owner. Makes strategic decisions. Wants to maximise sale price, diversify markets, reduce dependence on one or two traders and gain visibility into the export team. Fears losing control and exposing pricing to competitors. How to speak: financial outcome, not features." },
          { kind: "h3", text: "S2 — Export Manager" },
          { kind: "p", text: "Technical lead. Knows every market, incoterm and sanitary clearance. Wants operational efficiency and clarity on current market pricing. Fears another tool that adds work. How to speak: practical demo, real use case. Time is the central argument." },
          { kind: "h3", text: "S3 — Packer Trader" },
          { kind: "p", text: "Runs day-to-day deals. Often the point of resistance. Fears being replaced. How to break it: Mundus doesn't replace the trader, it amplifies their reach. They still close the deal. Warning sign: when the trader is already interested and jumps to operations (asks for a demo, wants to upload an offer), don't force the interview script, use it as an immediate activation opportunity." },
          { kind: "h3", text: "B1 — Importer Owner or Director" },
          { kind: "p", text: "Decides on strategic suppliers. Wants to diversify origins, ensure quality and gain price and volume predictability. Fears quality surprises and suppliers without clearance for their market. Cost on Mundus: zero." },
          { kind: "h3", text: "B2 — Operational Buyer" },
          { kind: "p", text: "Executes daily purchases. Wants speed. Real interview quote: \"Traders don't reply in time. When they do, the offer is already gone.\" How to speak: speed and offer availability, not price." },
        ],
      },
      {
        kicker: "04 — PAINS SOLVED",
        title: "What Mundus solves",
        blocks: [
          { kind: "h3", text: "For Suppliers" },
          { kind: "table", head: ["Keyword", "What it solves", "Practical gain"], rows: [
            ["Intelligence", "Real-time demand and price visibility by market and protein.", "Knows what the market pays before closing. Stops leaving money on the table."],
            ["Reach", "Access to verified global buyers beyond current network.", "Reaches the Philippines, Indonesia and the Middle East without trade shows."],
            ["Control", "Centralised history: what was negotiated, by whom and at what price.", "Sees what the team is doing without asking. Decides with data."],
            ["Resilience", "Early visibility of demand in alternative markets.", "When the China quota closes, already knows where to move."],
            ["Zero risk", "No subscription. Pays 0.30% only when the deal closes.", "Tests without committing budget."],
          ]},
          { kind: "h3", text: "For Buyers" },
          { kind: "table", head: ["Keyword", "What it solves", "Practical gain"], rows: [
            ["Transparency", "Standardised offers: product, price, incoterm, port and specs.", "Glance and compare. No quote requests, no manual spreadsheet."],
            ["Trust", "Only verified meatpackers. No invisible intermediary.", "Negotiates directly with the producer. Sees SIF, plant number and history."],
            ["Speed", "Negotiation within parameters pre-defined by the packer.", "What takes 3 days of email happens in 10 minutes."],
            ["Active demand", "Can publish what they want to buy. Packers come to them.", "Inverts the logic: post the need and the market responds."],
            ["Zero cost", "Free access, no subscription.", "No risk to experiment."],
          ]},
        ],
      },
      {
        kicker: "05 — OBJECTIONS",
        title: "Common objections and how to answer",
        blocks: [
          { kind: "h3", text: "Suppliers" },
          { kind: "table", head: ["Objection", "How to answer"], rows: [
            ["\"I already have more clients than I can serve.\"", "Then you can choose who pays best. But only if you see all options. Today you sell to who you know, not necessarily who pays the most right now."],
            ["\"No time. My team is overloaded.\"", "You don't operate, your trader does. Mundus takes work off the team, it doesn't add. And you get visibility without entering every conversation."],
            ["\"I'd rather wait until things stabilise.\"", "That's why there's no subscription. You only pay when you close. Zero risk to try. The risk of waiting while a competitor is already inside is another story."],
            ["\"No buyer for my specific protein.\"", "That's exactly the data Mundus has: what's being demanded, in which market and at what price. Worth checking what's active right now."],
            ["\"I won't put my clients in there.\"", "The platform does not expose your client to competitors. You see market demands, not your buyer's contact."],
            ["\"I already send plenty of email and it works.\"", "It works because it's the only way that exists. When the buyer can see every offer in one place without waiting for your email, what changes for you?"],
            ["\"Never heard of Mundus. Why trust it?\"", "Mundus was created by Fernando Nascimento, who has worked in international meat trade for over 28 years through WMS Foods. The platform launches with the credibility of someone who has already closed deals with buyers in China, the Middle East, Europe and the Americas."],
          ]},
          { kind: "h3", text: "Buyers" },
          { kind: "table", head: ["Objection", "How to answer"], rows: [
            ["\"The platform is empty. Not enough offers.\"", "You can post what you need to buy now. Packers see that demand and respond with targeted offers. You don't need to wait for the platform to fill up."],
            ["\"I have my fixed suppliers.\"", "Doesn't mean switching. Means having options when yours can't deliver or the price is off. It's free supply insurance."],
            ["\"I prefer email.\"", "By email you wait days. Here you get a reply in minutes. And the offer doesn't vanish because the trader was busy."],
            ["\"How do I know the packers are verified?\"", "Each supplier passes documentary verification before posting. You see SIF, plant number and history. Also, the platform was created by Fernando Nascimento, who has worked in the sector for over 28 years through WMS Foods."],
            ["\"I already work with WMS Foods. Why use another platform?\"", "Mundus is the natural evolution of that relationship: same credibility, more transparency, more options and more speed. And you access it all for free."],
          ]},
        ],
      },
      {
        kicker: "06 — TONE OF VOICE",
        title: "Brand personality and language",
        blocks: [
          { kind: "p", text: "Mundus speaks to professionals who have spent their entire careers in international meat trade. They are not beginners. They have 10, 20, 30 years in the market, consolidated relationships and healthy scepticism toward tech novelties. Mundus does not try to look like a tech startup: it is a platform built by someone who knows the sector from the inside." },
          { kind: "table", head: ["Speaks like this", "Never speaks like this"], rows: [
            ["Direct, no fluff", "Vague marketing clichés"],
            ["Numbers and data when they exist", "\"We are leaders in innovation\""],
            ["Industry vocabulary: SIF, incoterm, bid, DDP, FOB", "Generic tech language"],
            ["Respects the listener's intelligence", "Condescending or overly pedagogical tone"],
            ["Provokes the status quo: why do you still do it that way?", "Pushy or fairground-salesman tone"],
            ["Includes the buyer as protagonist, not as a user", "Focus only on platform features"],
            ["Talks about the market moment: those who enter now have an edge", "\"Join us today\" with no real context"],
            ["Specific and contextual to the sector", "Content that could come from any company"],
          ]},
          { kind: "h3", text: "Phrases that represent the brand" },
          { kind: "ul", items: [
            "\"You send 300 emails a day to place one offer. Mundus sends it to everyone at once.\"",
            "\"What today takes 3 days of email happens in 10 minutes.\"",
            "\"When the China quota closes, those already on Mundus already know where to move.\"",
            "\"Negotiate directly with the packer. No middleman. No price surprises.\"",
            "\"0.30% only when the deal closes. If it doesn't close, it cost nothing.\"",
            "\"You post what you need to buy. The packers come to you.\"",
          ]},
          { kind: "h3", text: "What AI must never do when speaking for Mundus" },
          { kind: "ul", items: [
            "Use startup vocabulary: 'disruption', 'ecosystem', 'user journey', 'synergy'.",
            "Promise unproven results.",
            "Use em-dashes (---) instead of punctuation. Looks AI-generated.",
            "Overuse emojis in LinkedIn or B2B email.",
            "Assume the reader is Brazilian. Mundus is global.",
            "Generalise suppliers as 'Brazilian meatpackers'.",
            "Cite platform features as the main argument. The argument is always the outcome for the client.",
            "Position Mundus as a trading or intermediary. Mundus is neutral and facilitates direct negotiation between the parties.",
          ]},
        ],
      },
      {
        kicker: "07 — CHANNELS",
        title: "Digital presence and channel strategy",
        blocks: [
          { kind: "p", text: "Mundus is a pioneer in a segment that has not yet been digitised. The market is not actively looking for a solution like it. Content must create the problem in the reader's mind before presenting the solution." },
          { kind: "callout", text: "Ideal sequence: (1) show the pain of the current way; (2) provoke with a question or data point; (3) present Mundus as the natural way out, without pushing." },
          { kind: "table", head: ["Channel", "Priority audience", "Tone and goal"], rows: [
            ["LinkedIn", "Packers and importers in Europe and the Americas. B2B in general.", "Education and credibility. Analytical posts. End with a question. English first, with some Portuguese."],
            ["Instagram", "Middle East, young industry audience.", "Visual, behind-the-scenes, trade-show presence. Reels with market data. Wine and dark-grey identity."],
            ["WhatsApp", "Middle East and individual business contacts.", "Short, direct messages. Never mass content."],
            ["WeChat", "China.", "Specific channel for Chinese buyers. Adapted language."],
            ["YouTube", "Future phase, when proof cases exist.", "Platform demos, testimonials and tutorials."],
          ]},
          { kind: "h3", text: "Current presence diagnosis (2025/2026 reference)" },
          { kind: "table", head: ["Channel", "Status"], rows: [
            ["LinkedIn", "Around 900 followers. Good copy quality. Lacks regularity, concrete data and sequential narrative between posts."],
            ["Instagram", "Around 189 followers. Consistent wine and burgundy visual identity. Zero Reels. Low frequency. No hashtag strategy."],
            ["Current phase", "Awareness and education. The market still doesn't understand what Mundus is. Communication's job now is to create problem awareness before presenting the solution."],
          ]},
          { kind: "h3", text: "Golden rule: external vs. internal" },
          { kind: "table", head: ["External content (public)", "Internal content (logged-in only)"], rows: [
            ["Institutional video: sparks curiosity, doesn't show features", "Step-by-step platform videos"],
            ["Market posts and sector data", "Help Center and usage tutorials"],
            ["Credibility and positioning narrative", "Full product demos"],
          ]},
        ],
      },
      {
        kicker: "08 — MARKETS",
        title: "Markets and geographies",
        blocks: [
          { kind: "p", text: "Mundus is a global marketplace with no geographic restriction. Packers from any country can register as suppliers. Buyers from any region can register and buy." },
          { kind: "h3", text: "Buyer markets" },
          { kind: "ul", items: [
            "China: largest meat importer in the world. WeChat as B2B channel.",
            "Middle East: Saudi Arabia, UAE, Pakistan. WhatsApp and Instagram.",
            "Asia: Philippines, Indonesia, Japan, South Korea.",
            "Europe: importers and distributors. LinkedIn and email.",
            "Americas: USA, Caribbean, Latin America.",
            "Africa: growing markets for more affordable proteins.",
          ]},
          { kind: "h3", text: "Supplier markets" },
          { kind: "p", text: "Initial network concentrated in Brazil but open to packers from Argentina, Uruguay, Australia, New Zealand, Eastern Europe, India, Ukraine and any other exporting country." },
          { kind: "callout", text: "IMPORTANT: never assume supplier equals Brazilian meatpacker. Mundus is global. Non-negotiable correction in any generated content." },
        ],
      },
      {
        kicker: "09 — COMPETITION",
        title: "Competitive context",
        blocks: [
          { kind: "p", text: "Mundus has no direct competitor in 2026. No other global platform connects packers and importers in a B2B marketplace model with negotiation inside the platform. Whoever arrives first and builds density defines the industry standard." },
          { kind: "table", head: ["Service / company", "Why it's not the same"], rows: [
            ["Email and WhatsApp", "Current market method. Not a platform. Mundus replaces that flow."],
            ["Trade shows (Gulfood, SIAL)", "In-person relationship building. Mundus complements, doesn't replace."],
            ["Datamar", "Sells export data with 20-30 day delay. Not a marketplace, doesn't connect parties."],
            ["Trade Cafe", "Trading company with its own platform, not a neutral marketplace."],
            ["Generic agri platforms", "Not specialised in animal proteins. Lack sector vocabulary and flows."],
          ]},
        ],
      },
      {
        kicker: "10 — TEAM",
        title: "Mundus Team",
        blocks: [
          { kind: "table", head: ["Member", "Role"], rows: [
            ["Fernando Nascimento", "Founder and CEO. Over 28 years in international meat trade (Minerva, WMS Foods). Based in Miami. Public face of Mundus. Network of 100+ meatpackers and 2,500+ global buyer contacts."],
            ["Débora", "Partner. Finance and administration. Analytical profile. Co-runs WMS Foods."],
            ["Gustavo Cândido", "Commercial and operations. Co-executor of activation actions. Day-to-day interface with packers and buyers."],
            ["Jennifer", "WMS Foods operations. Supports activation execution: organising and uploading offers on the platform."],
            ["Alexandre", "IT-focused partner. Tracks platform development."],
          ]},
        ],
      },
      {
        kicker: "11 — RULES FOR AI",
        title: "Mandatory reading before executing",
        blocks: [
          { kind: "h3", text: "Confirm before generating any content" },
          { kind: "ul", items: [
            "Which persona? (Packer owner, export manager, trader, buyer?)",
            "Which channel? (LinkedIn, Instagram, WhatsApp, email?)",
            "What goal? (Awareness, signup, offer activation, demand activation, onboarding?)",
            "Which language? (Portuguese, English, Spanish, Arabic?)",
            "For supplier, buyer or both?",
          ]},
          { kind: "h3", text: "Non-negotiable rules" },
          { kind: "ul", items: [
            "Mundus is global. Suppliers are not exclusively Brazilian.",
            "Mundus is not a trading. It does not buy or sell meat.",
            "The buyer never pays. The 0.30% commission is supplier-only.",
            "Never use em-dashes. Use comma, period or colon.",
            "Never generate generic content. If it could fit any company, it doesn't fit.",
            "Never cite tech features as the main argument. The argument is the client's outcome.",
            "Never promise unproven results.",
            "Never position Mundus as an intermediary. It is neutral and facilitates direct negotiation between the parties.",
          ]},
          { kind: "h3", text: "Forbidden phrases" },
          { kind: "ul", items: [
            "\"Innovative solution for your business.\"",
            "\"Transform your operation.\"",
            "\"We are leaders in disruption.\"",
            "\"Click here to learn more.\"",
            "Any phrase that could be published by a company in any other industry.",
          ]},
        ],
      },
      {
        kicker: "12 — GLOSSARY",
        title: "Industry glossary",
        blocks: [
          { kind: "table", head: ["Term", "Meaning in Mundus context"], rows: [
            ["Supplier", "Meatpacker that sells and exports. Posts offers. Pays 0.30% on close."],
            ["Buyer", "Importer or purchase trader. Searches offers or posts demand. Free access."],
            ["SIF", "Brazilian Federal Inspection Service. Certifies the packer for export. Equivalents exist in other countries."],
            ["Incoterm", "International commerce terms. Define who pays freight and up to which point. Ex.: FOB, CIF, DDP."],
            ["FOB", "Free on Board: seller delivers at origin port. Buyer pays international freight."],
            ["CIF", "Cost, Insurance and Freight: seller pays freight and insurance up to destination port."],
            ["DDP", "Delivered Duty Paid: seller delivers at final destination, including duties."],
            ["Container", "Refrigerated cargo unit. Typically 20 to 27 tonnes."],
            ["Bid", "Buyer's purchase proposal in response to an offer."],
            ["Sanitary clearance", "Importing country's authorisation for a packer to export."],
            ["Quota", "Country import limit per origin. Ex.: China quota for Brazilian beef."],
            ["Trading", "Intermediary company. Mundus is NOT a trading."],
            ["Protein", "Product category. Beef, pork, poultry, lamb, fish."],
            ["Cut", "Specific part of the animal. Striploin, flank, shoulder, picanha."],
            ["Meatpacker", "Company that processes and packs meat for export."],
            ["WMS Foods", "Fernando Nascimento's trading company. Origin of the network and credibility anchor for Mundus."],
            ["Gulfood", "Largest food trade show in the world (Dubai). Relevant for the Middle East."],
            ["SIAL", "International food show (Paris). Relevant for Europe."],
            ["Chemical Lean (CL)", "Meat fat percentage. Relevant for US and European markets."],
            ["Datamar", "Sells Brazilian export data with 20-30 day delay. Mundus surpasses it with real-time data."],
            ["Mundus Beef Index", "Mundus future product: real-time price and volume index by protein, cut, market and origin. No equivalent in the sector today."],
          ]},
        ],
      },
      {
        kicker: "13 — MAINTENANCE",
        title: "Keeping this document up to date",
        blocks: [
          { kind: "p", text: "This is a living document. It must be reviewed whenever there is a relevant change. Whoever leads each area is responsible for updating it. The most recent version must be the only one in circulation." },
          { kind: "table", head: ["What changed", "Sections to review", "Who updates"], rows: [
            ["New platform feature", "How it works, Pains solved", "Fernando or product"],
            ["New geographic market", "Audience, Markets", "Fernando or Gustavo"],
            ["Change in commission or pricing", "How it works, Pains, Rules for AI", "Fernando"],
            ["New team member", "Team", "Management"],
            ["New learning about a persona", "Audience, Objections, Tone of voice", "Whoever ran the interview"],
            ["Relevant competitor emerges", "Competitive context", "Fernando"],
            ["Proven success case", "Pains solved, Objections (social proof)", "Gustavo or Fernando"],
            ["Channel strategy change", "Digital channels", "Marketing"],
          ]},
          { kind: "h3", text: "Version history" },
          { kind: "table", head: ["Version", "Date and main changes"], rows: [
            ["v1.0", "April 2026. Initial version: identity, personas, benefits, tone of voice, channels, markets, competitive, team, rules for AI and glossary."],
            ["v1.1", "May 2026. Repositioning as a real-time data layer (Mundus Beef Index). WMS Foods credentials as trust anchor. Team update. New objections and neutral-positioning rule. External vs. internal content rule. Glossary expansion."],
            ["v2.0", "2026. Consolidated into the platform admin docs. Expanded WMS story (2,500 buyers), future block (Mundus Beef Index), presence diagnosis, maintenance section and team update (Jennifer)."],
          ]},
        ],
      },
    ],
  },

  es: {
    tagline: "Brandbook institucional — referencia interna",
    hero: "Identidad, posicionamiento, modelo de negocio y directrices de comunicación de Mundus Trade.",
    badge: "DOCUMENTO INTERNO | OPERADORES MUNDUS | 2026",
    print: "Imprimir / Guardar PDF",
    footer_kicker: "Mundus Trade",
    footer_lines: [
      "Mundus Trade LLC · Ocoee, Florida, USA",
      "Documento vivo · Versión 2.0",
      "Actualice cuando cambie estrategia, producto, público o mensaje",
    ],
    signature: "MUNDUS TRADE | BRANDBOOK INTERNO | 2026",
    sections: [
      {
        kicker: "00 — CÓMO USAR",
        title: "Cómo usar este documento",
        blocks: [
          { kind: "lede", text: "Este brandbook tiene dos papeles a la vez: es el documento de referencia interna de Mundus Trade y el archivo que cualquier herramienta de IA debe recibir antes de ejecutar cualquier tarea de marca." },
          { kind: "callout", text: "Instrucción para IA: antes de ejecutar cualquier tarea de Mundus Trade, lea este documento en su totalidad. No asuma información que no esté aquí. Si falta algo, pregunte al usuario." },
        ],
      },
      {
        kicker: "01 — IDENTIDAD",
        title: "Qué es Mundus Trade",
        blocks: [
          { kind: "p", text: "Mundus Trade es un marketplace B2B global para la exportación e importación de proteínas animales. Conecta frigoríficos (suppliers) de cualquier país del mundo con importadores, traders y compradores (buyers) de China, Medio Oriente, Asia, Europa, África y América." },
          { kind: "p", text: "Mundus no es una trading. No compra ni vende carne. Es el canal digital donde los frigoríficos publican ofertas y los buyers encuentran, negocian y cierran negocio directamente con el productor, sin intermediario." },
          { kind: "p", text: "Mundus es también una capa de datos en tiempo real: al centralizar negociaciones globales de proteínas animales, genera inteligencia de mercado que ningún otro servicio del sector ofrece con esa velocidad y granularidad." },
          { kind: "h3", text: "Datos corporativos" },
          { kind: "table", head: ["Campo", "Valor"], rows: [
            ["Razón social", "Mundus Trade LLC"],
            ["Sede", "Ocoee, Florida, USA"],
            ["Fundador", "Fernando Nascimento"],
            ["Lanzamiento", "17 de noviembre de 2024"],
            ["Modelo de ingreso", "Comisión del 0,30% sobre el valor cerrado. Sin mensualidad. Sin costo de registro."],
            ["Costo para el buyer", "Gratuito. El buyer nunca paga nada."],
          ]},
          { kind: "h3", text: "Misión" },
          { kind: "p", text: "Digitalizar y democratizar el comercio internacional de proteínas animales, conectando directamente a frigoríficos y compradores del mundo entero con transparencia, velocidad e inteligencia de mercado en tiempo real." },
          { kind: "h3", text: "Visión" },
          { kind: "p", text: "Ser la principal plataforma global de negociación de proteínas animales y la referencia de inteligencia de mercado del sector, haciendo el B2B tan simple y eficiente como cualquier marketplace moderno." },
          { kind: "h3", text: "Valores" },
          { kind: "ul", items: [
            "Transparencia: precio, historial y datos de mercado visibles dentro de la plataforma.",
            "Eficiencia: lo que hoy lleva días de e-mail debe ocurrir en minutos.",
            "Confianza: proveedores verificados, sin sorpresas de calidad o documentación.",
            "Neutralidad: Mundus no toma partido. Facilita el negocio sin sustituir la relación comercial.",
            "Alcance global: suppliers y buyers de cualquier país son bienvenidos.",
            "Inteligencia de mercado: datos reales, en tiempo real, para mejores decisiones de ambos lados.",
          ]},
          { kind: "callout", text: "Posicionamiento en una frase: el lugar donde los frigoríficos del mundo entero encuentran compradores globales, negocian y cierran con velocidad y transparencia, sin intermediario." },
        ],
      },
      {
        kicker: "02 — CÓMO FUNCIONA",
        title: "El modelo de marketplace",
        blocks: [
          { kind: "p", text: "Mundus opera como marketplace de dos lados: los suppliers publican ofertas y los buyers publican demanda. El sistema cruza esos datos y facilita la negociación directa entre las partes." },
          { kind: "table", head: ["Etapa", "Supplier", "Buyer"], rows: [
            ["Registro", "Registra operaciones, proteínas, volúmenes, mercados habilitados y documentación sanitaria.", "Registra empresa, mercados de interés y productos que demanda."],
            ["Publicación", "Publica ofertas con specs técnicas, precio, incoterm, puerto y SIF.", "Publica demandas abiertas: qué comprar, volumen y specs."],
            ["Negociación", "Responde bids y recibe propuestas en la plataforma, con historial.", "Envía bids, responde ofertas y negocia directo con el frigorífico."],
            ["Cierre", "Cierra el negocio. Comisión del 0,30% sobre el valor cerrado.", "Acceso gratuito. El buyer no paga nada."],
          ]},
          { kind: "h3", text: "Futuro: inteligencia de mercado como producto" },
          { kind: "p", text: "Cuando Mundus acumule volumen de transacciones, tendrá algo que ningún otro servicio del sector tiene hoy: datos de precios y volúmenes negociados en tiempo real, por proteína, corte, mercado y origen. Hoy Datamar vende datos con 20-30 días de atraso; Mundus los tendrá en vivo." },
          { kind: "h3", text: "Lo que Mundus NO es" },
          { kind: "ul", items: [
            "No es una trading: no compra ni vende carne.",
            "No es un broker: no representa a ninguna parte.",
            "No se limita a Brasil: los suppliers vienen de cualquier país.",
            "No es un ERP ni sistema de gestión.",
            "Sin mensualidad: modelo 100% basado en resultado.",
          ]},
          { kind: "callout", text: "Nunca asuma que los suppliers de Mundus son sólo brasileños. La plataforma es global. Frigoríficos de Argentina, Uruguay, Australia, Europa Oriental, India, Ucrania y cualquier otro país exportador forman parte del público." },
        ],
      },
      {
        kicker: "03 — PÚBLICO",
        title: "Personas de suppliers y buyers",
        blocks: [
          { kind: "h3", text: "S1 — Dueño o Director del Frigorífico" },
          { kind: "p", text: "CEO o dueño. Toma decisiones estratégicas. Quiere maximizar precio de venta y diversificar mercados. Teme perder control y exponer precios. Cómo hablar: resultado financiero, no funcionalidad." },
          { kind: "h3", text: "S2 — Gerente de Exportación" },
          { kind: "p", text: "Responsable técnico. Conoce cada mercado, incoterm y habilitación. Quiere eficiencia operativa. Cómo hablar: demo práctica, caso real." },
          { kind: "h3", text: "S3 — Trader del Frigorífico" },
          { kind: "p", text: "Ejecuta negociaciones. Suele ser el punto de resistencia. Teme ser sustituido. Cómo romperla: Mundus no sustituye al trader, amplifica su alcance." },
          { kind: "h3", text: "B1 — Dueño o Director del Importador" },
          { kind: "p", text: "Decide sobre proveedores estratégicos. Quiere diversificar y garantizar calidad. Costo: cero." },
          { kind: "h3", text: "B2 — Comprador Operativo" },
          { kind: "p", text: "Ejecuta las compras. Quiere velocidad. Cómo hablar: velocidad y disponibilidad, no precio." },
        ],
      },
      {
        kicker: "04 — DOLORES",
        title: "Lo que Mundus resuelve",
        blocks: [
          { kind: "h3", text: "Para Suppliers" },
          { kind: "table", head: ["Palabra clave", "Qué resuelve", "Ganancia"], rows: [
            ["Inteligencia", "Visibilidad de demanda y precios en tiempo real.", "Sabe qué paga el mercado antes de cerrar."],
            ["Alcance", "Acceso a compradores verificados globales.", "Llega a Filipinas, Indonesia y Medio Oriente sin feria."],
            ["Control", "Historial centralizado de negociaciones.", "Ve qué hace el equipo sin preguntar."],
            ["Resiliencia", "Visibilidad anticipada de demanda en mercados alternativos.", "Cuando la cuota de China cierra, ya sabe a dónde mover."],
            ["Riesgo cero", "Sin mensualidad. Paga 0,30% sólo al cerrar.", "Prueba sin comprometer presupuesto."],
          ]},
          { kind: "h3", text: "Para Buyers" },
          { kind: "table", head: ["Palabra clave", "Qué resuelve", "Ganancia"], rows: [
            ["Transparencia", "Ofertas estandarizadas: producto, precio, incoterm, puerto, specs.", "Compara de un vistazo, sin pedir cotización."],
            ["Confianza", "Sólo frigoríficos verificados. Sin intermediario.", "Negocia directo con el productor."],
            ["Velocidad", "Negociación dentro de parámetros pre-definidos.", "Lo que toma 3 días de e-mail ocurre en 10 minutos."],
            ["Demanda activa", "Puede publicar lo que quiere comprar.", "Invierte la lógica: el mercado responde."],
            ["Costo cero", "Acceso gratuito.", "Ningún riesgo para experimentar."],
          ]},
        ],
      },
      {
        kicker: "05 — OBJECIONES",
        title: "Objeciones comunes y cómo responder",
        blocks: [
          { kind: "h3", text: "Suppliers" },
          { kind: "table", head: ["Objeción", "Cómo responder"], rows: [
            ["\"Ya tengo más clientes de los que puedo atender.\"", "Entonces puede elegir quién paga más. Pero sólo si ve todas las opciones."],
            ["\"No tengo tiempo. Mi equipo está sobrecargado.\"", "Usted no opera, su trader opera. Mundus quita trabajo, no agrega."],
            ["\"Prefiero esperar a estar más estable.\"", "Por eso no hay mensualidad. Sólo paga al cerrar. Riesgo cero."],
            ["\"No tengo buyer para mi proteína.\"", "Esa es justo la información que Mundus tiene: qué se demanda, dónde y a qué precio."],
            ["\"No pondré a mis clientes ahí.\"", "La plataforma no expone su cliente al competidor. Ve demandas, no contactos."],
            ["\"Nunca oí hablar de Mundus. ¿Por qué confiar?\"", "Mundus fue creada por Fernando Nascimento, con más de 28 años en el comercio internacional de carnes vía WMS Foods. Nace con la credibilidad de quien ya cerró negocios en China, Medio Oriente, Europa y América."],
          ]},
          { kind: "h3", text: "Buyers" },
          { kind: "table", head: ["Objeción", "Cómo responder"], rows: [
            ["\"La plataforma está vacía.\"", "Puede publicar lo que necesita comprar. Los frigoríficos responden con oferta dirigida."],
            ["\"Ya tengo mis proveedores fijos.\"", "Tener Mundus no significa cambiar, significa tener opciones. Es un seguro de suministro, gratis."],
            ["\"Prefiero negociar por e-mail.\"", "Por e-mail espera días. Aquí responde en minutos."],
            ["\"¿Cómo sé que los frigoríficos están verificados?\"", "Cada supplier pasa por verificación documental. Ve SIF, número de planta e historial."],
            ["\"Ya trabajo con WMS Foods. ¿Para qué otra plataforma?\"", "Mundus es la evolución natural de esa relación: misma credibilidad, más transparencia, más opciones y más velocidad. Y gratis."],
          ]},
        ],
      },
      {
        kicker: "06 — TONO DE VOZ",
        title: "Personalidad y lenguaje de la marca",
        blocks: [
          { kind: "p", text: "Mundus habla con profesionales que pasaron toda su carrera en el comercio internacional de carnes. No son principiantes. Tienen 10, 20, 30 años en el mercado, relaciones consolidadas y escepticismo saludable hacia las novedades tecnológicas. Mundus no intenta parecer una startup: es una plataforma construida por alguien que conoce el sector por dentro." },
          { kind: "table", head: ["Habla así", "Nunca habla así"], rows: [
            ["Directo, sin rodeos", "Marketing vago y cliché"],
            ["Números y datos cuando existen", "\"Somos líderes en innovación\""],
            ["Vocabulario del sector: SIF, incoterm, bid, DDP, FOB", "Lenguaje genérico de tecnología"],
            ["Respeta la inteligencia del interlocutor", "Tono condescendiente"],
            ["Incluye al buyer como protagonista", "Foco sólo en funcionalidad"],
            ["Provoca el status quo", "Presión directa de vendedor"],
          ]},
          { kind: "h3", text: "Lo que la IA nunca debe hacer" },
          { kind: "ul", items: [
            "Usar vocabulario de startup: 'disrupción', 'ecosistema', 'sinergia'.",
            "Prometer resultados no comprobados.",
            "Usar guion largo (---) en lugar de puntuación.",
            "Asumir que el interlocutor es brasileño. Mundus es global.",
            "Generalizar a los suppliers como 'frigoríficos brasileños'.",
            "Citar funcionalidad técnica como argumento principal.",
            "Posicionar a Mundus como trading o intermediaria. Es neutra.",
          ]},
        ],
      },
      {
        kicker: "07 — CANALES",
        title: "Presencia digital",
        blocks: [
          { kind: "callout", text: "Secuencia ideal: (1) mostrar el dolor del modo actual; (2) provocar con dato o pregunta; (3) presentar Mundus como salida natural." },
          { kind: "table", head: ["Canal", "Público prioritario", "Tono y objetivo"], rows: [
            ["LinkedIn", "Frigoríficos e importadores de Europa y América.", "Educación y credibilidad. Posts analíticos."],
            ["Instagram", "Medio Oriente, público joven.", "Visual, bastidores, ferias. Reels con dato."],
            ["WhatsApp", "Medio Oriente y contactos individuales.", "Mensajes cortos y directos."],
            ["WeChat", "China.", "Canal específico para compradores chinos."],
            ["YouTube", "Fase futura.", "Demos, testimonios y tutoriales."],
          ]},
        ],
      },
      {
        kicker: "08 — MERCADOS",
        title: "Mercados y geografías",
        blocks: [
          { kind: "ul", items: [
            "China — WeChat como canal B2B.",
            "Medio Oriente — Arabia Saudita, EAU, Pakistán.",
            "Asia — Filipinas, Indonesia, Japón, Corea del Sur.",
            "Europa — LinkedIn y e-mail.",
            "América — EEUU, Caribe, Latinoamérica.",
            "África — mercados en crecimiento.",
          ]},
          { kind: "callout", text: "IMPORTANTE: nunca asumir que supplier = frigorífico brasileño. Mundus es global. Corrección no negociable." },
        ],
      },
      {
        kicker: "09 — COMPETENCIA",
        title: "Contexto competitivo",
        blocks: [
          { kind: "p", text: "Mundus no tiene competidor directo en 2026. No existe otra plataforma global que conecte frigoríficos e importadores en modelo de marketplace B2B con negociación dentro de la plataforma." },
          { kind: "table", head: ["Servicio", "Por qué no es lo mismo"], rows: [
            ["E-mail y WhatsApp", "Método actual. No es plataforma. Mundus sustituye ese flujo."],
            ["Ferias (Gulfood, SIAL)", "Relación presencial. Mundus complementa."],
            ["Datamar", "Datos con 20-30 días de atraso. No es marketplace."],
            ["Trade Cafe", "Trading con plataforma propia, no marketplace neutro."],
            ["Plataformas agrícolas genéricas", "No especializadas en proteínas animales."],
          ]},
        ],
      },
      {
        kicker: "10 — EQUIPO",
        title: "Equipo Mundus",
        blocks: [
          { kind: "table", head: ["Miembro", "Rol"], rows: [
            ["Fernando Nascimento", "Fundador y CEO. Más de 28 años en carnes. Cara pública de Mundus."],
            ["Débora", "Socia. Finanzas y administración."],
            ["Gustavo Cândido", "Comercial y operación."],
            ["Jennifer", "Operación WMS Foods. Organización y carga de ofertas en la plataforma."],
            ["Alexandre", "Socio con foco en TI."],
          ]},
        ],
      },
      {
        kicker: "11 — REGLAS PARA IA",
        title: "Obligatorio leer antes de ejecutar",
        blocks: [
          { kind: "h3", text: "Reglas no negociables" },
          { kind: "ul", items: [
            "Mundus es global. Suppliers no son exclusivamente brasileños.",
            "Mundus no es una trading.",
            "El buyer nunca paga. La comisión del 0,30% es exclusiva del supplier.",
            "Nunca usar guion largo.",
            "Nunca generar contenido genérico.",
            "Nunca citar funcionalidad técnica como argumento central.",
            "Nunca prometer resultados no comprobados.",
            "Nunca posicionar a Mundus como intermediaria. Es neutra.",
          ]},
        ],
      },
      {
        kicker: "12 — GLOSARIO",
        title: "Glosario del sector",
        blocks: [
          { kind: "table", head: ["Término", "Significado"], rows: [
            ["Supplier", "Frigorífico que vende y exporta. Paga 0,30% al cerrar."],
            ["Buyer", "Importador o trader. Acceso gratuito."],
            ["SIF", "Servicio de Inspección Federal (Brasil)."],
            ["Incoterm", "Términos internacionales: FOB, CIF, DDP."],
            ["Container", "Unidad de carga refrigerada. 20-27 toneladas."],
            ["Bid", "Propuesta de compra."],
            ["Cuota", "Límite de importación por origen."],
            ["Trading", "Empresa intermediaria. Mundus NO es una trading."],
            ["Proteína", "Categoría: bovina, porcina, pollo, ovina, pescado."],
            ["Datamar", "Datos brasileños con 20-30 días de atraso."],
            ["Mundus Beef Index", "Producto futuro: índice de precios y volúmenes en tiempo real, por proteína, corte, mercado y origen."],
          ]},
        ],
      },
    ],
  },

  zh: {
    tagline: "品牌手册 — 内部参考",
    hero: "Mundus Trade 的身份、定位、商业模式与传播指南。",
    badge: "内部文件 | MUNDUS 运营团队 | 2026",
    print: "打印 / 保存 PDF",
    footer_kicker: "Mundus Trade",
    footer_lines: [
      "Mundus Trade LLC · 美国佛罗里达州 Ocoee",
      "活文档 · 2.0 版",
      "战略、产品、受众或信息发生变化时请更新",
    ],
    signature: "MUNDUS TRADE | 内部品牌手册 | 2026",
    sections: [
      {
        kicker: "00 — 如何使用",
        title: "如何使用本文件",
        blocks: [
          { kind: "lede", text: "本品牌手册具有双重作用：既是 Mundus Trade 的内部参考文件，也是任何 AI 工具在执行与品牌相关任务前必须读取的文件。" },
          { kind: "callout", text: "AI 指令：执行任何与 Mundus Trade 相关的任务前，必须完整阅读本文件。不要假设此处未列出的信息。如缺少信息，先向用户提问。" },
        ],
      },
      {
        kicker: "01 — 身份",
        title: "什么是 Mundus Trade",
        blocks: [
          { kind: "p", text: "Mundus Trade 是全球动物蛋白进出口的 B2B 市场平台。它将全球任意国家的屠宰场（供应商）与中国、中东、亚洲、欧洲、非洲和美洲的进口商、贸易商和买家直接连接。" },
          { kind: "p", text: "Mundus 不是贸易商。它不买不卖任何肉类。它是供应商发布报价、买家直接与生产商查找、洽谈并成交的数字渠道，无需中间人。" },
          { kind: "p", text: "Mundus 同时是一个实时数据层：通过集中全球动物蛋白交易，生成本行业其他服务无法以此速度和粒度提供的市场情报。" },
          { kind: "h3", text: "公司信息" },
          { kind: "table", head: ["项目", "内容"], rows: [
            ["法人名称", "Mundus Trade LLC"],
            ["总部", "美国佛罗里达州 Ocoee"],
            ["创始人", "Fernando Nascimento"],
            ["平台上线", "2024 年 11 月 17 日"],
            ["收入模式", "成交金额的 0.30% 佣金。无月费。无注册费。"],
            ["买家费用", "免费。买家永远不付费。"],
          ]},
          { kind: "h3", text: "使命" },
          { kind: "p", text: "数字化并普及动物蛋白国际贸易，以透明、速度和实时市场情报直接连接全球屠宰场与买家。" },
          { kind: "h3", text: "愿景" },
          { kind: "p", text: "成为全球领先的动物蛋白交易平台和行业市场情报标杆，使本行业 B2B 与任何现代市场一样简单高效。" },
          { kind: "h3", text: "价值观" },
          { kind: "ul", items: [
            "透明：平台内可见价格、历史与市场数据。",
            "高效：今天耗时数日的邮件流程应在几分钟内完成。",
            "信任：经过认证的供应商，无质量或文件意外。",
            "中立：Mundus 不偏袒任何一方。",
            "全球覆盖：欢迎来自任何国家的供应商和买家。",
            "市场情报：真实、实时的数据，助力双方更好决策。",
          ]},
          { kind: "callout", text: "一句话定位：来自世界各地的屠宰场在此找到全球买家，以速度与透明度直接成交，无中间人。" },
        ],
      },
      {
        kicker: "02 — 如何运作",
        title: "市场平台模型",
        blocks: [
          { kind: "p", text: "Mundus 采用双边市场模型：供应商发布报价，买家发布需求。系统交叉这些数据，便于双方直接谈判。" },
          { kind: "table", head: ["阶段", "供应商", "买家"], rows: [
            ["注册", "登记运营、蛋白种类、产量、许可市场及卫生文件。", "登记公司、目标市场和所需产品。"],
            ["发布", "发布带技术规格、价格、贸易术语、港口和 SIF 号的报价。", "发布需求：要买什么、数量和规格。"],
            ["谈判", "在平台内回应出价并接收报价，全程留痕。", "提交出价、回应报价，直接与屠宰场谈判。"],
            ["成交", "完成交易。按成交金额收取 0.30% 佣金。", "免费使用，不付任何费用。"],
          ]},
          { kind: "h3", text: "未来：市场情报作为产品" },
          { kind: "p", text: "当 Mundus 积累交易量后，将拥有本行业其他服务今天没有的东西：按蛋白、部位、市场和产地的实时成交价格与数量数据。Datamar 今天出售延迟 20-30 天的数据；Mundus 将实时拥有这些数据。" },
          { kind: "h3", text: "Mundus 不是什么" },
          { kind: "ul", items: [
            "不是贸易商：从不买卖肉类。",
            "不是经纪人：不代表任何一方。",
            "不限于巴西：供应商来自任何国家。",
            "不是 ERP 或屠宰场管理系统。",
            "无月费：100% 按成果计费。",
          ]},
          { kind: "callout", text: "切勿假设 Mundus 的供应商仅来自巴西。平台是全球性的。阿根廷、乌拉圭、澳大利亚、东欧、印度、乌克兰及任何其他出口国的屠宰场都是 Mundus 的对象。" },
        ],
      },
      {
        kicker: "03 — 受众",
        title: "供应商与买家画像",
        blocks: [
          { kind: "h3", text: "S1 — 屠宰场所有者或董事" },
          { kind: "p", text: "CEO 或所有者。做战略决策。希望最大化售价、多元化市场。害怕失去控制并向竞争对手暴露价格。沟通方式：财务结果，而非功能。" },
          { kind: "h3", text: "S2 — 出口经理" },
          { kind: "p", text: "技术负责人。熟悉每个市场、贸易术语和卫生许可。希望操作高效。沟通方式：实操演示，真实案例。" },
          { kind: "h3", text: "S3 — 屠宰场贸易员" },
          { kind: "p", text: "执行日常谈判。常常是阻力点。害怕被取代。化解方法：Mundus 不取代贸易员，而是放大其触达。" },
          { kind: "h3", text: "B1 — 进口商所有者或董事" },
          { kind: "p", text: "决定战略供应商。希望多元化、保证质量。在 Mundus 上的成本：零。" },
          { kind: "h3", text: "B2 — 操作型买家" },
          { kind: "p", text: "执行采购。追求速度。沟通方式：速度与可得性，而非价格。" },
        ],
      },
      {
        kicker: "04 — 解决的痛点",
        title: "Mundus 解决什么",
        blocks: [
          { kind: "h3", text: "对供应商" },
          { kind: "table", head: ["关键词", "解决什么", "实际收益"], rows: [
            ["情报", "实时按市场和蛋白种类查看需求与价格。", "成交前知道市场价格，不再让利。"],
            ["触达", "接触全球经认证买家，超出现有网络。", "无需展会即可触达菲律宾、印尼和中东。"],
            ["控制", "集中化的谈判历史。", "无需询问即可看到团队工作进度。"],
            ["韧性", "对替代市场需求的提前可见性。", "中国配额关闭时已知何处可转。"],
            ["零风险", "无月费，仅成交后支付 0.30%。", "无预算压力即可试用。"],
          ]},
          { kind: "h3", text: "对买家" },
          { kind: "table", head: ["关键词", "解决什么", "实际收益"], rows: [
            ["透明", "标准化报价：产品、价格、贸易术语、港口和规格。", "一目了然地比较，无需询价。"],
            ["信任", "仅经认证的屠宰场，无隐形中间人。", "直接与生产商谈判，查看 SIF、工厂号和历史。"],
            ["速度", "在屠宰场预设参数内谈判。", "原来三天的邮件，10 分钟内完成。"],
            ["主动需求", "可发布采购需求，屠宰场上门。", "逆转逻辑：发布需求，市场响应。"],
            ["零成本", "免费访问，无订阅。", "无风险尝试。"],
          ]},
        ],
      },
      {
        kicker: "05 — 异议",
        title: "常见异议与回应",
        blocks: [
          { kind: "h3", text: "供应商" },
          { kind: "table", head: ["异议", "如何回应"], rows: [
            ["\"我已有应接不暇的客户。\"", "那您可以选择出价更高的，但前提是能看到所有选项。"],
            ["\"没时间，团队已超负荷。\"", "您不亲自操作，贸易员才操作。Mundus 减少工作量，不增加。"],
            ["\"我想等更稳定再试。\"", "正因如此没有月费，仅成交后付费，零风险。"],
            ["\"我的特定蛋白没有买家。\"", "Mundus 拥有的正是这种数据：什么在被需求、在哪个市场、什么价格。"],
            ["\"从没听说过 Mundus，为何信任？\"", "Mundus 由 Fernando Nascimento 创立，他通过 WMS Foods 在国际肉类贸易领域工作超过 28 年，平台天生具备已在中国、中东、欧洲和美洲成交的信誉。"],
          ]},
          { kind: "h3", text: "买家" },
          { kind: "table", head: ["异议", "如何回应"], rows: [
            ["\"平台是空的。\"", "您可以现在就发布需求，屠宰场会用定向报价回应。"],
            ["\"我已有固定供应商。\"", "不意味更换，意味当您的供应商无法满足时有选择。免费供应保险。"],
            ["\"我更愿意用邮件谈判。\"", "用邮件要等几天，这里几分钟内有回应。"],
            ["\"我如何知道屠宰场是经认证的？\"", "每位供应商发布前都经过文档验证。您可看到 SIF、工厂号和平台历史。"],
            ["\"我已与 WMS Foods 合作，为何还要用另一个平台？\"", "Mundus 是这段关系的自然延伸：同样的信誉、更高的透明度、更多选择和更快速度，且免费。"],
          ]},
        ],
      },
      {
        kicker: "06 — 语调",
        title: "品牌个性与语言",
        blocks: [
          { kind: "p", text: "Mundus 面对的是在国际肉类贸易领域工作了一辈子的专业人士。他们不是新手，有 10、20、30 年经验，关系稳固，对技术新潮持健康的怀疑。Mundus 不试图像科技初创公司：它是由真正了解行业内部的人构建的平台。" },
          { kind: "table", head: ["这样说", "绝不这样说"], rows: [
            ["直接，不绕弯", "模糊的营销陈词"],
            ["有数据时用数据", "\"我们是创新领导者\""],
            ["行业词汇：SIF、贸易术语、bid、DDP、FOB", "通用科技语言"],
            ["尊重对方的智识", "居高临下或过于说教"],
            ["将买家视为主角", "只关注平台功能"],
            ["挑战现状", "推销式或集市式语气"],
          ]},
          { kind: "h3", text: "AI 代表 Mundus 发声时绝不可" },
          { kind: "ul", items: [
            "使用初创术语：'颠覆'、'生态'、'用户旅程'、'协同'。",
            "承诺未经证实的结果。",
            "用破折号 (---) 代替标点。",
            "假设对话者是巴西人。Mundus 是全球的。",
            "把供应商一概概括为\"巴西屠宰场\"。",
            "把技术功能作为核心论点。论点始终是客户结果。",
            "把 Mundus 定位为贸易商或中间人。它是中立的。",
          ]},
        ],
      },
      {
        kicker: "07 — 渠道",
        title: "数字存在与渠道策略",
        blocks: [
          { kind: "callout", text: "理想序列：(1) 展示现状之痛；(2) 用数据或问题挑战；(3) 自然地呈现 Mundus 作为出路。" },
          { kind: "table", head: ["渠道", "优先受众", "语调与目标"], rows: [
            ["LinkedIn", "欧美屠宰场和进口商。B2B 一般。", "教育与信誉。分析型贴文。以英语为主。"],
            ["Instagram", "中东，行业年轻受众。", "视觉、幕后、展会。带数据的 Reels。酒红与深灰色识别。"],
            ["WhatsApp", "中东及个别商务联系。", "简短直接。不做群发。"],
            ["WeChat", "中国。", "中国买家专属渠道。本地化语言。"],
            ["YouTube", "未来阶段。", "平台演示、证言和教程。"],
          ]},
        ],
      },
      {
        kicker: "08 — 市场",
        title: "市场与地理",
        blocks: [
          { kind: "ul", items: [
            "中国 — 微信为 B2B 渠道。",
            "中东 — 沙特、阿联酋、巴基斯坦。",
            "亚洲 — 菲律宾、印尼、日本、韩国。",
            "欧洲 — LinkedIn 与邮件。",
            "美洲 — 美国、加勒比、拉美。",
            "非洲 — 经济型蛋白的增长市场。",
          ]},
          { kind: "callout", text: "重要：切勿假设供应商 = 巴西屠宰场。Mundus 是全球的。此项纠正不可妥协。" },
        ],
      },
      {
        kicker: "09 — 竞争",
        title: "竞争格局",
        blocks: [
          { kind: "p", text: "Mundus 在 2026 年没有直接竞争对手。没有其他全球平台以 B2B 市场模式连接屠宰场和进口商，并在平台内完成谈判。先到者构建用户密度，将定义行业标准。" },
          { kind: "table", head: ["服务/公司", "为何不同"], rows: [
            ["邮件和 WhatsApp", "市场现行方法。非平台。Mundus 取代该流程。"],
            ["展会（Gulfood、SIAL）", "线下关系建立。Mundus 是补充，不是替代。"],
            ["Datamar", "出售延迟 20-30 天的出口数据。非市场，不连接双方。"],
            ["Trade Cafe", "自有平台的贸易公司，非中立市场。"],
            ["通用农业平台", "不专注于动物蛋白出口。缺乏行业词汇和流程。"],
          ]},
        ],
      },
      {
        kicker: "10 — 团队",
        title: "Mundus 团队",
        blocks: [
          { kind: "table", head: ["成员", "角色"], rows: [
            ["Fernando Nascimento", "创始人兼 CEO。28 年以上国际肉类贸易经验。Mundus 的公众形象。"],
            ["Débora", "合伙人。财务与行政。"],
            ["Gustavo Cândido", "商务与运营。"],
            ["Jennifer", "WMS Foods 运营。在平台上组织并上传报价。"],
            ["Alexandre", "技术方向的合伙人。"],
          ]},
        ],
      },
      {
        kicker: "11 — AI 规则",
        title: "执行前必读",
        blocks: [
          { kind: "h3", text: "不可妥协的规则" },
          { kind: "ul", items: [
            "Mundus 是全球的，供应商并非仅来自巴西。",
            "Mundus 不是贸易商。",
            "买家永远不付费。0.30% 佣金仅向供应商收取。",
            "切勿使用破折号。",
            "切勿生成通用内容。",
            "切勿把技术功能作为核心论点。",
            "切勿承诺未经证实的结果。",
            "切勿把 Mundus 定位为中间人。它是中立的。",
          ]},
        ],
      },
      {
        kicker: "12 — 术语表",
        title: "行业术语",
        blocks: [
          { kind: "table", head: ["术语", "含义"], rows: [
            ["Supplier", "销售与出口的屠宰场。成交时支付 0.30%。"],
            ["Buyer", "进口商或采购贸易员。免费访问。"],
            ["SIF", "巴西联邦检验服务。其他国家有对应机构。"],
            ["Incoterm", "国际贸易术语：FOB、CIF、DDP。"],
            ["Container", "冷藏货柜。通常 20-27 吨。"],
            ["Bid", "买家对报价的采购提议。"],
            ["Quota", "进口国对来源地的进口限额。"],
            ["Trading", "中间贸易公司。Mundus 不是贸易商。"],
            ["Protein", "产品类别：牛、猪、禽、羊、鱼。"],
            ["Datamar", "出售延迟 20-30 天的巴西出口数据。Mundus 以实时数据超越之。"],
            ["Mundus Beef Index", "Mundus 未来产品：按蛋白、部位、市场和产地的实时价格与数量指数。"],
          ]},
        ],
      },
    ],
  },
};

export function BrandbookDocument() {
  return <AdminDocView content={CONTENT} />;
}
