import { Fragment, useState, type ReactNode } from "react";
import { Link } from "react-router-dom";
import { useTranslation } from "react-i18next";
import { useToast } from "@/hooks/use-toast";
import { Tabs, TabPanel } from "@/components/mundus/Tabs";
import { ShipmentTracker } from "@/components/shipment/ShipmentTracker";
import { ShippingInstructionsCard } from "@/components/shipping/ShippingInstructionsCard";
import { StatusBadge, ShippingStatusTracker, getStatusConfig } from "@/lib/orderStatus";
import { supabase } from "@/integrations/supabase/client";
import { useEffect } from "react";
import {
  FileTextIcon,
  ArrowLeftIcon,
  ArrowsLeftRightIcon,
  ShipIcon,
  FileIcon,
  MessageIcon,
  DownloadIcon,
  UploadIcon,
  EyeIcon,
  CheckCircleIcon,
  MapPinIcon,
  ClockIcon,
  DollarIcon,
  KnifeForkIcon,
  UserIcon,
  SparkleIcon,
} from "@/components/icons";

export type DealParty = {
  name: string;
  country?: string;
  flagEmoji?: string;
};

export type DealCut = {
  name: string;
  weightKg: number;
  pricePerKgUsd: number;
  floorPerKgUsd?: number;
  askingPerKgUsd?: number;
  rounds?: Array<{ bidPerKgUsd?: number | null; counterPerKgUsd?: number | null }>;
  subItems?: string[];
};

export type DealNegotiationRound = {
  round: number;
  buyerBidUsd: number;
  counterUsd: number;
  accepted?: boolean;
  at?: string;
};

export type DealNegotiation = {
  initialAskingUsd: number;
  firstBuyerBidUsd: number;
  rounds: DealNegotiationRound[];
  closedAt?: string;
  openFullHref?: string;
};

export type DealShipmentContainer = {
  containerNo: string;
  sealNo?: string;
  booking?: string;
  blNumber?: string;
  vessel?: string;
  voyage?: string;
  portLoading?: string;
  portDischarge?: string;
  etd?: string;
  eta?: string;
  grossKg?: number;
  netKg?: number;
  temperature?: string;
};

export type DealJourneyStage =
  | "booked" | "loading" | "departed" | "in_transit"
  | "arrived" | "discharged" | "delivered";

export type DealDocumentItem = {
  id: string;
  category: "trade" | "shipping" | "quality" | "compliance";
  name: string;
  required?: boolean;
  uploadedAt?: string;
  sizeKb?: number;
  fileName?: string;
};

export type DealDocuments = {
  autoGenerated: { salesOrder?: string; purchaseOrder?: string };
  items: DealDocumentItem[];
};

export type DealStatus = {
  label: string;
  tone: "pending" | "info" | "success" | "danger";
};

export type DealTimelineStage = {
  key: "created" | "pre_payment" | "production" | "shipment" | "delivery";
  label: string;
  value: string;
  tone?: "muted" | "info" | "success" | "danger";
};

export type DealDetailData = {
  role: "buyer" | "supplier";
  dealNumber: string;
  date: string;
  fcls: number;
  totalKg: number;
  product: string;
  totalValueUsd: number;
  status: DealStatus;
  rawStatus?: string;
  statusUpdatedAt?: string;
  party: DealParty;
  overview: {
    date: string;
    totalValueUsd: number;
    origin: string;
    destination: string;
    incoterm?: string;
    container: string; // e.g. "1× 40ft FCL"
    totalVolume: string; // e.g. "27.000 kg"
    shipmentMonth?: string;
    species?: string;
    temperature?: string;
  };
  cuts: DealCut[];
  timeline: DealTimelineStage[];
  negotiation?: DealNegotiation;
  containers: DealShipmentContainer[];
  journeyStage: DealJourneyStage;
  documents: DealDocuments;
  backHref: string;
  fullNegotiationHref?: string;
  orderId?: string;
  shipmentReadOnly?: boolean;
};

type TabKey = "overview" | "negotiation" | "shipment" | "documents";

function fmtKg(v: number) {
  return new Intl.NumberFormat("de-DE", { maximumFractionDigits: 0 }).format(v);
}
function fmtUsd(v: number) {
  return `US$ ${new Intl.NumberFormat("de-DE", { minimumFractionDigits: 2, maximumFractionDigits: 2 }).format(v)}`;
}
function fmtUsdPerKg(v: number) {
  return `$${v.toFixed(2)}`;
}

function initials(name: string) {
  return name
    .split(/\s+/)
    .filter(Boolean)
    .slice(0, 2)
    .map((w) => w[0]?.toUpperCase() ?? "")
    .join("");
}

const STAGE_ORDER: DealJourneyStage[] = [
  "booked", "loading", "departed", "in_transit", "arrived", "discharged", "delivered",
];

function FieldGrid({ children }: { children: ReactNode }) {
  return <div className="ddv-field-grid">{children}</div>;
}
function Field({ label, value }: { label: string; value: ReactNode }) {
  return (
    <div className="ddv-field">
      <span className="ddv-field-lbl">{label}</span>
      <span className="ddv-field-val">{value || "—"}</span>
    </div>
  );
}

function Card({
  title, icon: I, right, children,
}: {
  title?: string;
  icon?: React.ComponentType<{ size?: number }>;
  right?: ReactNode;
  children: ReactNode;
}) {
  return (
    <section className="ddv-card">
      {(title || right) && (
        <header className="ddv-card-head">
          {title && (
            <h3>
              {I && <I size={14} />}
              {title}
            </h3>
          )}
          {right && <span className="ddv-card-right">{right}</span>}
        </header>
      )}
      <div className="ddv-card-body">{children}</div>
    </section>
  );
}

export function DealDetailView({ data }: { data: DealDetailData }) {
  const { t } = useTranslation();
  const { toast } = useToast();
  const [tab, setTab] = useState<TabKey>("overview");
  const [containerIdx] = useState(0);
  const [liveStatus, setLiveStatus] = useState<string | undefined>(data.rawStatus);
  const [liveUpdatedAt, setLiveUpdatedAt] = useState<string | undefined>(data.statusUpdatedAt);

  useEffect(() => {
    setLiveStatus(data.rawStatus);
    setLiveUpdatedAt(data.statusUpdatedAt);
  }, [data.rawStatus, data.statusUpdatedAt]);

  useEffect(() => {
    if (!data.orderId) return;
    const channel = supabase
      .channel(`deal-status-${data.orderId}`)
      .on(
        "postgres_changes",
        { event: "UPDATE", schema: "public", table: "orders", filter: `id=eq.${data.orderId}` },
        (payload) => {
          const row = payload.new as { status?: string; updated_at?: string } | null;
          if (row?.status) setLiveStatus(row.status);
          if (row?.updated_at) setLiveUpdatedAt(row.updated_at);
        },
      )
      .subscribe();
    return () => { supabase.removeChannel(channel); };
  }, [data.orderId]);

  const currentStatus = liveStatus ?? data.rawStatus;

  const tk = (k: string, fallback: string, opts?: Record<string, unknown>) =>
    (t(k, { defaultValue: fallback, ...opts }) as string);

  const docsCount = data.documents.items.length;
  const docsDone = data.documents.items.filter((d) => d.uploadedAt).length;
  const docsRequiredCount = data.documents.items.filter((d) => d.required).length;
  const docsRequiredDone = data.documents.items.filter((d) => d.required && d.uploadedAt).length;
  const progressPct = docsCount === 0 ? 0 : Math.round((docsDone / docsCount) * 100);

  const tabs = [
    { value: "overview", label: tk("dealDetail.tabs.overview", "Overview") },
    { value: "negotiation", label: tk("dealDetail.tabs.negotiation", "Negotiation") },
    { value: "shipment", label: tk("dealDetail.tabs.shipment", "Shipment") },
    {
      value: "documents",
      label: `${tk("dealDetail.tabs.documents", "Documents")} ${docsDone}/${docsCount}`,
    },
  ];

  const partyHeaderLabel = data.role === "buyer"
    ? tk("dealDetail.party.supplier", "Supplier")
    : tk("dealDetail.party.buyer", "Buyer");

  const messagePartyLabel = data.role === "buyer"
    ? tk("dealDetail.party.messageSupplier", "Message supplier")
    : tk("dealDetail.party.messageBuyer", "Message buyer");

  const recordLabel = data.role === "buyer"
    ? tk("dealDetail.record.order", "Order")
    : tk("dealDetail.record.sale", "Sale");

  const stageIndex = STAGE_ORDER.indexOf(data.journeyStage);
  const journeyLabels: Record<DealJourneyStage, string> = {
    booked:      tk("dealDetail.journey.booked", "Booked"),
    loading:     tk("dealDetail.journey.loading", "Loading"),
    departed:    tk("dealDetail.journey.departed", "Departed"),
    in_transit:  tk("dealDetail.journey.inTransit", "In transit"),
    arrived:     tk("dealDetail.journey.arrived", "Arrived port"),
    discharged:  tk("dealDetail.journey.discharged", "Discharged"),
    delivered:   tk("dealDetail.journey.delivered", "Delivered"),
  };
  void stageIndex; void journeyLabels;

  const stub = (msg: string) => () => toast({ title: msg });

  const docCategories: DealDocumentItem["category"][] = [
    "trade", "shipping", "quality", "compliance",
  ];
  const catLabel: Record<DealDocumentItem["category"], string> = {
    trade: tk("dealDetail.docs.trade", "Trade"),
    shipping: tk("dealDetail.docs.shipping", "Shipping"),
    quality: tk("dealDetail.docs.quality", "Quality"),
    compliance: tk("dealDetail.docs.compliance", "Compliance"),
  };

  const c = data.containers[containerIdx] ?? data.containers[0];

  return (
    <div className="ddv">
      <Link to={data.backHref} className="ddv-back">
        <ArrowLeftIcon size={16} />
        {data.role === "buyer"
          ? tk("dealDetail.back.orders", "Back to orders")
          : tk("dealDetail.back.sales", "Back to sales")}
      </Link>

      <header className="ddv-head-card">
        <span className="ddv-head-thumb"><FileTextIcon size={20} /></span>
        <div className="ddv-head-meta">
          <h1>{recordLabel} #{data.dealNumber}</h1>
          <p className="ddv-head-sub">
            <span>{data.date}</span>
            <span className="dot">·</span>
            <span className="ddv-flag">{data.party.flagEmoji}</span>
            <span>{data.party.name}</span>
            <span className="dot">·</span>
            <span>{data.fcls}× FCL</span>
            <span className="dot">·</span>
            <span>{fmtKg(data.totalKg)} kg</span>
          </p>
        </div>
        <div className="ddv-head-right">
          <span className={`ddv-status ddv-status--${data.status.tone}`}>
            {data.status.label}
          </span>
          <span className="ddv-head-total">{fmtUsd(data.totalValueUsd)}</span>
        </div>
      </header>

      <Tabs
        items={tabs}
        value={tab}
        onChange={(v) => setTab(v as TabKey)}
        ariaLabel="deal-tabs"
      />

      <div className="ddv-layout">
        <div className="ddv-main">
          <TabPanel active={tab === "overview"}>
            <Card title={`${recordLabel.toUpperCase()} ${tk("dealDetail.section.details", "DETAILS")}`} icon={FileTextIcon}>
              <FieldGrid>
                <Field label={partyHeaderLabel.toUpperCase()} value={data.party.name} />
                <Field label={tk("dealDetail.fields.date", "Date")} value={data.overview.date} />
                <Field label={tk("dealDetail.fields.totalValue", "Total value")} value={fmtUsd(data.overview.totalValueUsd)} />
                <Field label={tk("dealDetail.fields.origin", "Origin")} value={<><span className="ddv-flag">{data.party.flagEmoji ? "🟢" : ""}</span>{data.overview.origin}</>} />
                <Field label={tk("dealDetail.fields.destination", "Destination")} value={data.overview.destination} />
                <Field label={tk("dealDetail.fields.incoterm", "Incoterm")} value={data.overview.incoterm || "—"} />
                <Field label={tk("dealDetail.fields.container", "Container")} value={data.overview.container} />
                <Field label={tk("dealDetail.fields.totalVolume", "Total volume")} value={data.overview.totalVolume} />
                <Field label={tk("dealDetail.fields.shipmentMonth", "Shipment month")} value={data.overview.shipmentMonth || "—"} />
                <Field label={tk("dealDetail.fields.speciesTemp", "Species · Temp")} value={`${data.overview.species ?? "—"} · ${data.overview.temperature ?? "—"}`} />
              </FieldGrid>
            </Card>

            <Card title={tk("dealDetail.section.cutsIncluded", "CUTS INCLUDED")} icon={KnifeForkIcon}>
              {data.cuts.map((cut, i) => (
                <div key={i} className="ddv-cut-row">
                  <span className="dot-bullet" />
                  <div className="ddv-cut-meta">
                    <strong>{cut.name}</strong>
                    {cut.subItems && cut.subItems.length > 0 && (
                      <span className="ddv-cut-sub">{cut.subItems.join(" · ")}</span>
                    )}
                  </div>
                  <span className="ddv-cut-qty">{fmtKg(cut.weightKg)} kg</span>
                  <span className="ddv-cut-price">{fmtUsdPerKg(cut.pricePerKgUsd)}/kg</span>
                </div>
              ))}
            </Card>
          </TabPanel>

          <TabPanel active={tab === "negotiation"}>
            {data.negotiation ? (() => {
              const neg = data.negotiation;
              const showFloor = data.role === "supplier";
              const totalKg = data.totalKg || 1;
              const askingPerKg = neg.initialAskingUsd / totalKg;
              // Build flat pill timeline: bid1 -> counter1 -> bid2 -> counter2 ...
              const pills: Array<{ type: "bid" | "counter"; round: number; totalUsd: number; current: boolean }> = [];
              neg.rounds.forEach((r, idx) => {
                const isLast = idx === neg.rounds.length - 1;
                pills.push({ type: "bid", round: r.round, totalUsd: r.buyerBidUsd, current: false });
                if (r.counterUsd) {
                  pills.push({ type: "counter", round: r.round, totalUsd: r.counterUsd, current: isLast });
                }
              });
              const maxRound = neg.rounds.length;
              return (
                <>
                  <div className="nd-card">
                    <div className="nd-timeline-head">
                      <span className="tl-head-title">
                        <SparkleIcon size={14} />
                        {tk("dealDetail.negotiation.timeline", "Round timeline")}
                      </span>
                      <Link
                        to={data.role === "supplier"
                          ? `/supplier/negotiations/${data.orderId}`
                          : `/buyer/negotiations/${data.orderId}`}
                        className="text-xs font-medium text-[#8B2252] hover:underline"
                      >
                        {tk("dealDetail.negotiation.openFull", "Open negotiation →")}
                      </Link>
                      <span className="tl-head-meta">
                        {tk("dealDetail.negotiation.roundOf", "Round {{round}} of {{max}}", { round: maxRound, max: maxRound })}
                      </span>
                    </div>
                    <div className="nd-timeline-flow">
                      {pills.map((p, i) => {
                        const labelKey = p.type === "bid"
                          ? tk("dealDetail.negotiation.pillBid", "Bid {{n}}", { n: p.round })
                          : p.current
                            ? tk("dealDetail.negotiation.pillCounterCurrent", "Counter {{n}}", { n: p.round })
                            : tk("dealDetail.negotiation.pillCounter", "Counter {{n}}", { n: p.round });
                        const cls = p.type === "bid"
                          ? "tl-pill tl-pill--bid"
                          : p.current
                            ? "tl-pill tl-pill--counter tl-pill--current"
                            : "tl-pill tl-pill--counter";
                        return (
                          <Fragment key={`${p.type}-${p.round}-${i}`}>
                            {i > 0 && <span className="tl-sep">→</span>}
                            <span className={cls}>
                              <span className="tl-pill-label">{labelKey}</span>
                              <span>{fmtUsd(p.totalUsd)}</span>
                            </span>
                          </Fragment>
                        );
                      })}
                    </div>
                  </div>

                  <div className="nd-card">
                    <div className="nd-card-head">
                      <strong>{tk("dealDetail.negotiation.priceDetails", "Price details")}</strong>
                      {neg.closedAt && (
                        <span className="nd-updated">{neg.closedAt}</span>
                      )}
                    </div>
                    <div className="nd-price-scroll-wrap" style={{ overflowX: "auto" }}>
                      <table className="nd-price-table">
                        <thead>
                          <tr>
                            <th>{tk("dealDetail.negotiation.col.product", "Product")}</th>
                            <th>{tk("dealDetail.negotiation.col.qty", "Qty (kg)")}</th>
                            <th>{tk("dealDetail.negotiation.col.asking", "Asking")}</th>
                            {showFloor && <th>{tk("dealDetail.negotiation.col.floor", "Floor")}</th>}
                            {Array.from({ length: maxRound }, (_, i) => (
                              <Fragment key={`h-${i}`}>
                                <th className="col-bid">{tk("dealDetail.negotiation.col.bidR", "Bid R{{n}}", { n: i + 1 })}</th>
                                <th className="col-counter">{tk("dealDetail.negotiation.col.counterR", "Counter R{{n}}", { n: i + 1 })}</th>
                              </Fragment>
                            ))}
                          </tr>
                        </thead>
                        <tbody>
                          {data.cuts.map((cut, ci) => {
                            const cutAsking = cut.askingPerKgUsd ?? askingPerKg;
                            return (
                              <tr key={ci} style={{ background: "rgba(34,197,94,0.06)" }}>
                                <td>
                                  <span className="product-name">🔒 {cut.name}</span>
                                  {cut.subItems && cut.subItems.length > 0 && (
                                    <span className="product-pack">{cut.subItems.join(" · ")}</span>
                                  )}
                                  <span
                                    className="inline-block ml-1 mt-1 px-2 py-0.5 rounded-full text-[10px] font-medium"
                                    style={{ background: "rgba(34,197,94,0.15)", color: "#15803d" }}
                                  >
                                    {tk("dealDetail.negotiation.agreedAt", "Agreed at ${{price}}/kg", { price: cut.pricePerKgUsd.toFixed(2) })}
                                  </span>
                                </td>
                                <td>{fmtKg(cut.weightKg)}</td>
                                <td>{fmtUsdPerKg(cutAsking)}</td>
                                {showFloor && (
                                  <td>{cut.floorPerKgUsd != null ? fmtUsdPerKg(cut.floorPerKgUsd) : "—"}</td>
                                )}
                                {Array.from({ length: maxRound }, (_, i) => {
                                  const r = cut.rounds?.[i];
                                  const isLast = i === maxRound - 1;
                                  const bidV = r?.bidPerKgUsd;
                                  const cntV = r?.counterPerKgUsd;
                                  return (
                                    <Fragment key={`v-${ci}-${i}`}>
                                      <td className="col-bid">{bidV != null ? fmtUsdPerKg(bidV) : "—"}</td>
                                      <td
                                        className={`col-counter${isLast ? " col-counter--current" : ""}`}
                                        style={isLast ? { color: "#15803d", fontWeight: 600 } : undefined}
                                      >
                                        {isLast
                                          ? `${fmtUsdPerKg(cut.pricePerKgUsd)} 🔒`
                                          : cntV != null
                                            ? fmtUsdPerKg(cntV)
                                            : "—"}
                                      </td>
                                    </Fragment>
                                  );
                                })}
                              </tr>
                            );
                          })}
                        </tbody>
                      </table>
                    </div>
                  </div>
                </>
              );
            })() : (
              <Card title={tk("dealDetail.negotiation.howClosed", "HOW THIS DEAL CLOSED")} icon={ArrowsLeftRightIcon}>
                <p className="ddv-empty">{tk("dealDetail.negotiation.none", "No negotiation rounds recorded.")}</p>
              </Card>
            )}
          </TabPanel>

          <TabPanel active={tab === "shipment"}>
            {data.orderId ? (
              <ShipmentTracker
                orderId={data.orderId}
                fclCount={data.fcls || 1}
                readOnly={data.shipmentReadOnly}
              />
            ) : (
              <Card title={tk("dealDetail.shipment.info", "SHIPMENT INFORMATION")} icon={ShipIcon}>
                <p style={{ color: "var(--muted)", padding: "8px 0" }}>
                  {tk("dealDetail.shipment.unavailable", "Shipment tracking is not available for this record.")}
                </p>
              </Card>
            )}
          </TabPanel>

          <TabPanel active={tab === "documents"}>
            {data.orderId && (
              <ShippingInstructionsCard
                orderId={data.orderId}
                orderNumber={data.dealNumber}
                defaultBuyerName={data.role === "supplier" ? data.party.name : undefined}
                supplierName={data.role === "buyer" ? data.party.name : undefined}
                readOnly={data.shipmentReadOnly}
              />
            )}
            <Card
              title={tk("dealDetail.docs.autoGenerated", "ORDER DOCUMENTS — AUTO-GENERATED")}
              icon={CheckCircleIcon}
              right={
                <span className="ddv-card-sub">
                  {tk("dealDetail.docs.issuedClose", "Issued when deal closed")}
                </span>
              }
            >
              <div className="ddv-auto-grid">
                {data.documents.autoGenerated.salesOrder && (
                  <div className="ddv-auto-doc">
                    <FileTextIcon size={16} />
                    <div>
                      <strong>{tk("dealDetail.docs.so", "Sales Order (SO)")}</strong>
                      <span>{data.documents.autoGenerated.salesOrder}</span>
                    </div>
                    <button type="button" className="ddv-icon-btn" onClick={stub(tk("dealDetail.toast.download", "Download (mock)"))}>
                      <DownloadIcon size={16} />
                    </button>
                  </div>
                )}
                {data.documents.autoGenerated.purchaseOrder && (
                  <div className="ddv-auto-doc">
                    <FileTextIcon size={16} />
                    <div>
                      <strong>{tk("dealDetail.docs.po", "Purchase Order (PO)")}</strong>
                      <span>{data.documents.autoGenerated.purchaseOrder}</span>
                    </div>
                    <button type="button" className="ddv-icon-btn" onClick={stub(tk("dealDetail.toast.download", "Download (mock)"))}>
                      <DownloadIcon size={16} />
                    </button>
                  </div>
                )}
              </div>
            </Card>

            <div className="ddv-progress-card">
              <div className="ddv-progress-head">
                <span>{tk("dealDetail.docs.completion", "Documentation completion")}</span>
                <span>{progressPct}%</span>
              </div>
              <div className="ddv-progress-bar">
                <span style={{ width: `${progressPct}%` }} />
              </div>
            </div>

            {docCategories.map((cat) => {
              const items = data.documents.items.filter((d) => d.category === cat);
              if (items.length === 0) return null;
              const done = items.filter((d) => d.uploadedAt).length;
              return (
                <Card
                  key={cat}
                  title={catLabel[cat].toUpperCase()}
                  icon={FileIcon}
                  right={<span className="ddv-card-sub">{done} {tk("dealDetail.docs.of", "of")} {items.length}</span>}
                >
                  {items.map((doc) => (
                    <div key={doc.id} className="ddv-doc-row">
                      {doc.uploadedAt ? (
                        <CheckCircleIcon size={16} />
                      ) : (
                        <FileIcon size={16} />
                      )}
                      <div className="ddv-doc-meta">
                        <span className="ddv-doc-name">
                          <strong>{doc.name}</strong>
                          {doc.required && (
                            <span className="ddv-pill-required">{tk("dealDetail.docs.required", "REQUIRED")}</span>
                          )}
                        </span>
                        <span className="ddv-doc-sub">
                          {doc.uploadedAt
                            ? `${doc.fileName ?? ""} · ${doc.uploadedAt}${doc.sizeKb ? ` · ${doc.sizeKb} KB` : ""}`
                            : tk("dealDetail.docs.notUploaded", "Not uploaded yet")}
                        </span>
                      </div>
                      {doc.uploadedAt ? (
                        <span className="ddv-doc-actions">
                          <button type="button" className="ddv-btn-ghost" onClick={stub(tk("dealDetail.toast.view", "View document (mock)"))}>
                            <EyeIcon size={14} /> {tk("dealDetail.docs.view", "View")}
                          </button>
                          <button type="button" className="ddv-btn-ghost" onClick={stub(tk("dealDetail.toast.download", "Download (mock)"))}>
                            <DownloadIcon size={14} /> {tk("dealDetail.docs.download", "Download")}
                          </button>
                        </span>
                      ) : (
                        <button type="button" className="ddv-btn-primary" onClick={stub(tk("dealDetail.toast.upload", "Upload (mock)"))}>
                          <UploadIcon size={14} /> {tk("dealDetail.docs.upload", "Upload")}
                        </button>
                      )}
                    </div>
                  ))}
                </Card>
              );
            })}
          </TabPanel>
        </div>

        <aside className="ddv-side">
          {tab === "shipment" ? (
            <Card title={tk("dealDetail.shipment.route", "ROUTE")} icon={MapPinIcon}>
              <div className="ddv-route">
                <div className="ddv-route-point">
                  <span className="ddv-flag">🟢</span>
                  <div>
                    <strong>{c?.portLoading ?? "—"}</strong>
                    <span>ETD</span>
                    <span>{c?.etd ?? "—"}</span>
                  </div>
                </div>
                <div className="ddv-route-line" />
                <div className="ddv-route-point">
                  <span className="ddv-flag">🔴</span>
                  <div>
                    <strong>{c?.portDischarge ?? "—"}</strong>
                    <span>ETA</span>
                    <span>{c?.eta ?? "—"}</span>
                  </div>
                </div>
              </div>
              <div className="ddv-route-meta">
                <span>{c?.vessel ?? "—"}</span>
                <span>{tk("dealDetail.shipment.voyage", "Voyage")} {c?.voyage ?? "—"}</span>
              </div>
              <button type="button" className="ddv-btn-primary ddv-btn-block" onClick={stub(tk("dealDetail.toast.track", "Tracking (mock)"))}>
                <DownloadIcon size={14} /> {tk("dealDetail.shipment.trackCarrier", "Track on carrier")}
              </button>
            </Card>
          ) : tab === "negotiation" && data.negotiation ? (
            <>
              <Card title={tk("dealDetail.negotiation.totals", "TOTALS")} icon={DollarIcon}>
                <div className="ddv-side-row"><span>{tk("dealDetail.negotiation.initialAsking", "Initial asking")}</span><strong>{fmtUsd(data.negotiation.initialAskingUsd)}</strong></div>
                <div className="ddv-side-row"><span>{tk("dealDetail.negotiation.firstBuyerBid", "First buyer bid")}</span><strong className="blue">{fmtUsd(data.negotiation.firstBuyerBidUsd)}</strong></div>
                <div className="ddv-side-row"><span>{tk("dealDetail.negotiation.discountGiven", "Discount given")}</span><strong className="muted">−{fmtUsd(data.negotiation.initialAskingUsd - data.totalValueUsd)}</strong></div>
                <div className="ddv-divider" />
                <div className="ddv-side-row big"><span>{tk("dealDetail.negotiation.finalTotal", "Final total")}</span><strong className="accent">{fmtUsd(data.totalValueUsd)}</strong></div>
              </Card>
              {data.fullNegotiationHref && (
                <Link to={data.fullNegotiationHref} className="ddv-btn-ghost-block">
                  <MessageIcon size={14} /> {tk("dealDetail.negotiation.openFull", "Open full negotiation")}
                </Link>
              )}
            </>
          ) : (
            <>
              <Card title={partyHeaderLabel.toUpperCase()} icon={UserIcon}>
                <div className="ddv-party">
                  <span className="ddv-party-av">{initials(data.party.name)}</span>
                  <div className="ddv-party-meta">
                    <strong>{data.party.name}</strong>
                    {data.party.country && (
                      <span>
                        <span className="ddv-flag">{data.party.flagEmoji ?? "📍"}</span>
                        {data.party.country}
                      </span>
                    )}
                  </div>
                </div>
                <button type="button" className="ddv-btn-ghost ddv-btn-block" onClick={stub(tk("dealDetail.toast.message", "Open chat (mock)"))}>
                  <MessageIcon size={14} /> {messagePartyLabel}
                </button>
              </Card>

              <Card title={tk("dealDetail.timeline.title", "QUICK TIMELINE")} icon={ClockIcon}>
                {data.timeline.map((s) => (
                  <div key={s.key} className="ddv-tl-row">
                    <span>{s.label}</span>
                    <span className={`ddv-tl-val ddv-tl-val--${s.tone ?? "muted"}`}>{s.value}</span>
                  </div>
                ))}
              </Card>
            </>
          )}
        </aside>
      </div>
    </div>
  );
}
