import { useState, type ReactNode } from "react";
import { Link } from "react-router-dom";
import { useTranslation } from "react-i18next";
import { useToast } from "@/hooks/use-toast";
import { Tabs, TabPanel } from "@/components/mundus/Tabs";
import { ShipmentTracker } from "@/components/shipment/ShipmentTracker";
import { ShippingInstructionsCard } from "@/components/shipping/ShippingInstructionsCard";
import {
  FileTextIcon,
  ArrowLeftIcon,
  ArrowsLeftRightIcon,
  ShipIcon,
  FileIcon,
  MessageIcon,
  DownloadIcon,
  UploadIcon,
  EyeIcon,
  CheckCircleIcon,
  MapPinIcon,
  ClockIcon,
  DollarIcon,
  KnifeForkIcon,
  UserIcon,
} from "@/components/icons";

export type DealParty = {
  name: string;
  country?: string;
  flagEmoji?: string;
};

export type DealCut = {
  name: string;
  weightKg: number;
  pricePerKgUsd: number;
  subItems?: string[];
};

export type DealNegotiationRound = {
  round: number;
  buyerBidUsd: number;
  counterUsd: number;
  accepted?: boolean;
  at?: string;
};

export type DealNegotiation = {
  initialAskingUsd: number;
  firstBuyerBidUsd: number;
  rounds: DealNegotiationRound[];
  closedAt?: string;
  openFullHref?: string;
};

export type DealShipmentContainer = {
  containerNo: string;
  sealNo?: string;
  booking?: string;
  blNumber?: string;
  vessel?: string;
  voyage?: string;
  portLoading?: string;
  portDischarge?: string;
  etd?: string;
  eta?: string;
  grossKg?: number;
  netKg?: number;
  temperature?: string;
};

export type DealJourneyStage =
  | "booked" | "loading" | "departed" | "in_transit"
  | "arrived" | "discharged" | "delivered";

export type DealDocumentItem = {
  id: string;
  category: "trade" | "shipping" | "quality" | "compliance";
  name: string;
  required?: boolean;
  uploadedAt?: string;
  sizeKb?: number;
  fileName?: string;
};

export type DealDocuments = {
  autoGenerated: { salesOrder?: string; purchaseOrder?: string };
  items: DealDocumentItem[];
};

export type DealStatus = {
  label: string;
  tone: "pending" | "info" | "success" | "danger";
};

export type DealTimelineStage = {
  key: "created" | "pre_payment" | "production" | "shipment" | "delivery";
  label: string;
  value: string;
  tone?: "muted" | "info" | "success" | "danger";
};

export type DealDetailData = {
  role: "buyer" | "supplier";
  dealNumber: string;
  date: string;
  fcls: number;
  totalKg: number;
  product: string;
  totalValueUsd: number;
  status: DealStatus;
  party: DealParty;
  overview: {
    date: string;
    totalValueUsd: number;
    origin: string;
    destination: string;
    incoterm?: string;
    container: string; // e.g. "1× 40ft FCL"
    totalVolume: string; // e.g. "27.000 kg"
    shipmentMonth?: string;
    species?: string;
    temperature?: string;
  };
  cuts: DealCut[];
  timeline: DealTimelineStage[];
  negotiation?: DealNegotiation;
  containers: DealShipmentContainer[];
  journeyStage: DealJourneyStage;
  documents: DealDocuments;
  backHref: string;
  fullNegotiationHref?: string;
  orderId?: string;
  shipmentReadOnly?: boolean;
};

type TabKey = "overview" | "negotiation" | "shipment" | "documents";

function fmtKg(v: number) {
  return new Intl.NumberFormat("de-DE", { maximumFractionDigits: 0 }).format(v);
}
function fmtUsd(v: number) {
  return `US$ ${new Intl.NumberFormat("de-DE", { minimumFractionDigits: 2, maximumFractionDigits: 2 }).format(v)}`;
}
function fmtUsdPerKg(v: number) {
  return `$${v.toFixed(2)}`;
}

function initials(name: string) {
  return name
    .split(/\s+/)
    .filter(Boolean)
    .slice(0, 2)
    .map((w) => w[0]?.toUpperCase() ?? "")
    .join("");
}

const STAGE_ORDER: DealJourneyStage[] = [
  "booked", "loading", "departed", "in_transit", "arrived", "discharged", "delivered",
];

function FieldGrid({ children }: { children: ReactNode }) {
  return <div className="ddv-field-grid">{children}</div>;
}
function Field({ label, value }: { label: string; value: ReactNode }) {
  return (
    <div className="ddv-field">
      <span className="ddv-field-lbl">{label}</span>
      <span className="ddv-field-val">{value || "—"}</span>
    </div>
  );
}

function Card({
  title, icon: I, right, children,
}: {
  title?: string;
  icon?: React.ComponentType<{ size?: number }>;
  right?: ReactNode;
  children: ReactNode;
}) {
  return (
    <section className="ddv-card">
      {(title || right) && (
        <header className="ddv-card-head">
          {title && (
            <h3>
              {I && <I size={14} />}
              {title}
            </h3>
          )}
          {right && <span className="ddv-card-right">{right}</span>}
        </header>
      )}
      <div className="ddv-card-body">{children}</div>
    </section>
  );
}

export function DealDetailView({ data }: { data: DealDetailData }) {
  const { t } = useTranslation();
  const { toast } = useToast();
  const [tab, setTab] = useState<TabKey>("overview");
  const [containerIdx] = useState(0);

  const tk = (k: string, fallback: string, opts?: Record<string, unknown>) =>
    (t(k, { defaultValue: fallback, ...opts }) as string);

  const docsCount = data.documents.items.length;
  const docsDone = data.documents.items.filter((d) => d.uploadedAt).length;
  const docsRequiredCount = data.documents.items.filter((d) => d.required).length;
  const docsRequiredDone = data.documents.items.filter((d) => d.required && d.uploadedAt).length;
  const progressPct = docsCount === 0 ? 0 : Math.round((docsDone / docsCount) * 100);

  const tabs = [
    { value: "overview", label: tk("dealDetail.tabs.overview", "Overview") },
    { value: "negotiation", label: tk("dealDetail.tabs.negotiation", "Negotiation") },
    { value: "shipment", label: tk("dealDetail.tabs.shipment", "Shipment") },
    {
      value: "documents",
      label: `${tk("dealDetail.tabs.documents", "Documents")} ${docsDone}/${docsCount}`,
    },
  ];

  const partyHeaderLabel = data.role === "buyer"
    ? tk("dealDetail.party.supplier", "Supplier")
    : tk("dealDetail.party.buyer", "Buyer");

  const messagePartyLabel = data.role === "buyer"
    ? tk("dealDetail.party.messageSupplier", "Message supplier")
    : tk("dealDetail.party.messageBuyer", "Message buyer");

  const recordLabel = data.role === "buyer"
    ? tk("dealDetail.record.order", "Order")
    : tk("dealDetail.record.sale", "Sale");

  const stageIndex = STAGE_ORDER.indexOf(data.journeyStage);
  const journeyLabels: Record<DealJourneyStage, string> = {
    booked:      tk("dealDetail.journey.booked", "Booked"),
    loading:     tk("dealDetail.journey.loading", "Loading"),
    departed:    tk("dealDetail.journey.departed", "Departed"),
    in_transit:  tk("dealDetail.journey.inTransit", "In transit"),
    arrived:     tk("dealDetail.journey.arrived", "Arrived port"),
    discharged:  tk("dealDetail.journey.discharged", "Discharged"),
    delivered:   tk("dealDetail.journey.delivered", "Delivered"),
  };
  void stageIndex; void journeyLabels;

  const stub = (msg: string) => () => toast({ title: msg });

  const docCategories: DealDocumentItem["category"][] = [
    "trade", "shipping", "quality", "compliance",
  ];
  const catLabel: Record<DealDocumentItem["category"], string> = {
    trade: tk("dealDetail.docs.trade", "Trade"),
    shipping: tk("dealDetail.docs.shipping", "Shipping"),
    quality: tk("dealDetail.docs.quality", "Quality"),
    compliance: tk("dealDetail.docs.compliance", "Compliance"),
  };

  const c = data.containers[containerIdx] ?? data.containers[0];

  return (
    <div className="ddv">
      <Link to={data.backHref} className="ddv-back">
        <ArrowLeftIcon size={16} />
        {data.role === "buyer"
          ? tk("dealDetail.back.orders", "Back to orders")
          : tk("dealDetail.back.sales", "Back to sales")}
      </Link>

      <header className="ddv-head-card">
        <span className="ddv-head-thumb"><FileTextIcon size={20} /></span>
        <div className="ddv-head-meta">
          <h1>{recordLabel} #{data.dealNumber}</h1>
          <p className="ddv-head-sub">
            <span>{data.date}</span>
            <span className="dot">·</span>
            <span className="ddv-flag">{data.party.flagEmoji}</span>
            <span>{data.party.name}</span>
            <span className="dot">·</span>
            <span>{data.fcls}× FCL</span>
            <span className="dot">·</span>
            <span>{fmtKg(data.totalKg)} kg</span>
          </p>
        </div>
        <div className="ddv-head-right">
          <span className={`ddv-status ddv-status--${data.status.tone}`}>
            {data.status.label}
          </span>
          <span className="ddv-head-total">{fmtUsd(data.totalValueUsd)}</span>
        </div>
      </header>

      <Tabs
        items={tabs}
        value={tab}
        onChange={(v) => setTab(v as TabKey)}
        ariaLabel="deal-tabs"
      />

      <div className="ddv-layout">
        <div className="ddv-main">
          <TabPanel active={tab === "overview"}>
            <Card title={`${recordLabel.toUpperCase()} ${tk("dealDetail.section.details", "DETAILS")}`} icon={FileTextIcon}>
              <FieldGrid>
                <Field label={partyHeaderLabel.toUpperCase()} value={data.party.name} />
                <Field label={tk("dealDetail.fields.date", "Date")} value={data.overview.date} />
                <Field label={tk("dealDetail.fields.totalValue", "Total value")} value={fmtUsd(data.overview.totalValueUsd)} />
                <Field label={tk("dealDetail.fields.origin", "Origin")} value={<><span className="ddv-flag">{data.party.flagEmoji ? "🟢" : ""}</span>{data.overview.origin}</>} />
                <Field label={tk("dealDetail.fields.destination", "Destination")} value={data.overview.destination} />
                <Field label={tk("dealDetail.fields.incoterm", "Incoterm")} value={data.overview.incoterm || "—"} />
                <Field label={tk("dealDetail.fields.container", "Container")} value={data.overview.container} />
                <Field label={tk("dealDetail.fields.totalVolume", "Total volume")} value={data.overview.totalVolume} />
                <Field label={tk("dealDetail.fields.shipmentMonth", "Shipment month")} value={data.overview.shipmentMonth || "—"} />
                <Field label={tk("dealDetail.fields.speciesTemp", "Species · Temp")} value={`${data.overview.species ?? "—"} · ${data.overview.temperature ?? "—"}`} />
              </FieldGrid>
            </Card>

            <Card title={tk("dealDetail.section.cutsIncluded", "CUTS INCLUDED")} icon={KnifeForkIcon}>
              {data.cuts.map((cut, i) => (
                <div key={i} className="ddv-cut-row">
                  <span className="dot-bullet" />
                  <div className="ddv-cut-meta">
                    <strong>{cut.name}</strong>
                    {cut.subItems && cut.subItems.length > 0 && (
                      <span className="ddv-cut-sub">{cut.subItems.join(" · ")}</span>
                    )}
                  </div>
                  <span className="ddv-cut-qty">{fmtKg(cut.weightKg)} kg</span>
                  <span className="ddv-cut-price">{fmtUsdPerKg(cut.pricePerKgUsd)}/kg</span>
                </div>
              ))}
            </Card>
          </TabPanel>

          <TabPanel active={tab === "negotiation"}>
            {data.negotiation ? (
              <Card
                title={tk("dealDetail.negotiation.howClosed", "HOW THIS DEAL CLOSED")}
                icon={ArrowsLeftRightIcon}
                right={
                  data.negotiation.closedAt ? (
                    <span className="ddv-card-sub">
                      {tk("dealDetail.negotiation.closedAfter", "Closed after {{n}} rounds", { n: data.negotiation.rounds.length })}
                      {" · "}{data.negotiation.closedAt}
                    </span>
                  ) : null
                }
              >
                {data.negotiation.rounds.map((r) => {
                  const max = Math.max(r.buyerBidUsd, r.counterUsd, data.negotiation!.initialAskingUsd);
                  const bidPct = Math.max(8, Math.round((r.buyerBidUsd / max) * 100));
                  const cntPct = Math.max(8, Math.round((r.counterUsd / max) * 100));
                  return (
                    <div key={r.round} className={`ddv-round ${r.accepted ? "is-accepted" : ""}`}>
                      <div className="ddv-round-head">
                        <strong>{tk("dealDetail.negotiation.round", "Round")} {r.round}</strong>
                        {r.accepted && (
                          <span className="ddv-pill-success">
                            ★ {tk("dealDetail.negotiation.accepted", "ACCEPTED")}
                          </span>
                        )}
                        {r.at && <span className="ddv-round-at">{r.at}</span>}
                      </div>
                      <div className="ddv-bar-row">
                        <span className="ddv-bar-lbl">{tk("dealDetail.negotiation.buyerBid", "Buyer bid")}</span>
                        <div className="ddv-bar ddv-bar--blue" style={{ width: `${bidPct}%` }}>
                          <span>{fmtUsd(r.buyerBidUsd)}</span>
                        </div>
                      </div>
                      <div className="ddv-bar-row">
                        <span className="ddv-bar-lbl">
                          {data.role === "buyer"
                            ? tk("dealDetail.negotiation.supplierCounter", "Supplier counter")
                            : tk("dealDetail.negotiation.yourCounter", "Your counter")}
                        </span>
                        <div className="ddv-bar ddv-bar--rose" style={{ width: `${cntPct}%` }}>
                          <span>{fmtUsd(r.counterUsd)}</span>
                        </div>
                      </div>
                    </div>
                  );
                })}
              </Card>
            ) : (
              <Card title={tk("dealDetail.negotiation.howClosed", "HOW THIS DEAL CLOSED")} icon={ArrowsLeftRightIcon}>
                <p className="ddv-empty">{tk("dealDetail.negotiation.none", "No negotiation rounds recorded.")}</p>
              </Card>
            )}

            <Card title={tk("dealDetail.negotiation.finalPerCut", "FINAL PRICE PER CUT")} icon={DollarIcon}>
              <div className="ddv-final-table">
                <div className="ddv-final-head">
                  <span>{tk("dealDetail.cuts.cut", "Cut")}</span>
                  <span className="num">{tk("dealDetail.cuts.qty", "Qty")}</span>
                  <span className="num">{tk("dealDetail.cuts.asking", "Asking")}</span>
                  <span className="num">{tk("dealDetail.cuts.finalKg", "Final $/kg")}</span>
                  <span className="num">{tk("dealDetail.cuts.total", "Total")}</span>
                </div>
                {data.cuts.map((cut, i) => {
                  const asking = data.negotiation
                    ? (data.negotiation.initialAskingUsd / data.totalKg)
                    : cut.pricePerKgUsd;
                  return (
                    <div key={i} className="ddv-final-row">
                      <span>
                        <strong>{cut.name}</strong>
                        {cut.subItems && cut.subItems.length > 0 && (
                          <span className="ddv-cut-sub"> · {cut.subItems.join(" · ")}</span>
                        )}
                      </span>
                      <span className="num">{fmtKg(cut.weightKg)} kg</span>
                      <span className="num">{fmtUsdPerKg(asking)}</span>
                      <span className="num accent">{fmtUsdPerKg(cut.pricePerKgUsd)}</span>
                      <span className="num">{fmtUsd(cut.weightKg * cut.pricePerKgUsd)}</span>
                    </div>
                  );
                })}
              </div>
            </Card>
          </TabPanel>

          <TabPanel active={tab === "shipment"}>
            {data.orderId ? (
              <ShipmentTracker
                orderId={data.orderId}
                fclCount={data.fcls || 1}
                readOnly={data.shipmentReadOnly}
              />
            ) : (
              <Card title={tk("dealDetail.shipment.info", "SHIPMENT INFORMATION")} icon={ShipIcon}>
                <p style={{ color: "var(--muted)", padding: "8px 0" }}>
                  {tk("dealDetail.shipment.unavailable", "Shipment tracking is not available for this record.")}
                </p>
              </Card>
            )}
          </TabPanel>

          <TabPanel active={tab === "documents"}>
            {data.orderId && (
              <ShippingInstructionsCard
                orderId={data.orderId}
                orderNumber={data.dealNumber}
                defaultBuyerName={data.role === "supplier" ? data.party.name : undefined}
                supplierName={data.role === "buyer" ? data.party.name : undefined}
                readOnly={data.shipmentReadOnly}
              />
            )}
            <Card
              title={tk("dealDetail.docs.autoGenerated", "ORDER DOCUMENTS — AUTO-GENERATED")}
              icon={CheckCircleIcon}
              right={
                <span className="ddv-card-sub">
                  {tk("dealDetail.docs.issuedClose", "Issued when deal closed")}
                </span>
              }
            >
              <div className="ddv-auto-grid">
                {data.documents.autoGenerated.salesOrder && (
                  <div className="ddv-auto-doc">
                    <FileTextIcon size={16} />
                    <div>
                      <strong>{tk("dealDetail.docs.so", "Sales Order (SO)")}</strong>
                      <span>{data.documents.autoGenerated.salesOrder}</span>
                    </div>
                    <button type="button" className="ddv-icon-btn" onClick={stub(tk("dealDetail.toast.download", "Download (mock)"))}>
                      <DownloadIcon size={16} />
                    </button>
                  </div>
                )}
                {data.documents.autoGenerated.purchaseOrder && (
                  <div className="ddv-auto-doc">
                    <FileTextIcon size={16} />
                    <div>
                      <strong>{tk("dealDetail.docs.po", "Purchase Order (PO)")}</strong>
                      <span>{data.documents.autoGenerated.purchaseOrder}</span>
                    </div>
                    <button type="button" className="ddv-icon-btn" onClick={stub(tk("dealDetail.toast.download", "Download (mock)"))}>
                      <DownloadIcon size={16} />
                    </button>
                  </div>
                )}
              </div>
            </Card>

            <div className="ddv-progress-card">
              <div className="ddv-progress-head">
                <span>{tk("dealDetail.docs.completion", "Documentation completion")}</span>
                <span>{progressPct}%</span>
              </div>
              <div className="ddv-progress-bar">
                <span style={{ width: `${progressPct}%` }} />
              </div>
            </div>

            {docCategories.map((cat) => {
              const items = data.documents.items.filter((d) => d.category === cat);
              if (items.length === 0) return null;
              const done = items.filter((d) => d.uploadedAt).length;
              return (
                <Card
                  key={cat}
                  title={catLabel[cat].toUpperCase()}
                  icon={FileIcon}
                  right={<span className="ddv-card-sub">{done} {tk("dealDetail.docs.of", "of")} {items.length}</span>}
                >
                  {items.map((doc) => (
                    <div key={doc.id} className="ddv-doc-row">
                      {doc.uploadedAt ? (
                        <CheckCircleIcon size={16} />
                      ) : (
                        <FileIcon size={16} />
                      )}
                      <div className="ddv-doc-meta">
                        <span className="ddv-doc-name">
                          <strong>{doc.name}</strong>
                          {doc.required && (
                            <span className="ddv-pill-required">{tk("dealDetail.docs.required", "REQUIRED")}</span>
                          )}
                        </span>
                        <span className="ddv-doc-sub">
                          {doc.uploadedAt
                            ? `${doc.fileName ?? ""} · ${doc.uploadedAt}${doc.sizeKb ? ` · ${doc.sizeKb} KB` : ""}`
                            : tk("dealDetail.docs.notUploaded", "Not uploaded yet")}
                        </span>
                      </div>
                      {doc.uploadedAt ? (
                        <span className="ddv-doc-actions">
                          <button type="button" className="ddv-btn-ghost" onClick={stub(tk("dealDetail.toast.view", "View document (mock)"))}>
                            <EyeIcon size={14} /> {tk("dealDetail.docs.view", "View")}
                          </button>
                          <button type="button" className="ddv-btn-ghost" onClick={stub(tk("dealDetail.toast.download", "Download (mock)"))}>
                            <DownloadIcon size={14} /> {tk("dealDetail.docs.download", "Download")}
                          </button>
                        </span>
                      ) : (
                        <button type="button" className="ddv-btn-primary" onClick={stub(tk("dealDetail.toast.upload", "Upload (mock)"))}>
                          <UploadIcon size={14} /> {tk("dealDetail.docs.upload", "Upload")}
                        </button>
                      )}
                    </div>
                  ))}
                </Card>
              );
            })}
          </TabPanel>
        </div>

        <aside className="ddv-side">
          {tab === "shipment" ? (
            <Card title={tk("dealDetail.shipment.route", "ROUTE")} icon={MapPinIcon}>
              <div className="ddv-route">
                <div className="ddv-route-point">
                  <span className="ddv-flag">🟢</span>
                  <div>
                    <strong>{c?.portLoading ?? "—"}</strong>
                    <span>ETD</span>
                    <span>{c?.etd ?? "—"}</span>
                  </div>
                </div>
                <div className="ddv-route-line" />
                <div className="ddv-route-point">
                  <span className="ddv-flag">🔴</span>
                  <div>
                    <strong>{c?.portDischarge ?? "—"}</strong>
                    <span>ETA</span>
                    <span>{c?.eta ?? "—"}</span>
                  </div>
                </div>
              </div>
              <div className="ddv-route-meta">
                <span>{c?.vessel ?? "—"}</span>
                <span>{tk("dealDetail.shipment.voyage", "Voyage")} {c?.voyage ?? "—"}</span>
              </div>
              <button type="button" className="ddv-btn-primary ddv-btn-block" onClick={stub(tk("dealDetail.toast.track", "Tracking (mock)"))}>
                <DownloadIcon size={14} /> {tk("dealDetail.shipment.trackCarrier", "Track on carrier")}
              </button>
            </Card>
          ) : tab === "negotiation" && data.negotiation ? (
            <>
              <Card title={tk("dealDetail.negotiation.totals", "TOTALS")} icon={DollarIcon}>
                <div className="ddv-side-row"><span>{tk("dealDetail.negotiation.initialAsking", "Initial asking")}</span><strong>{fmtUsd(data.negotiation.initialAskingUsd)}</strong></div>
                <div className="ddv-side-row"><span>{tk("dealDetail.negotiation.firstBuyerBid", "First buyer bid")}</span><strong className="blue">{fmtUsd(data.negotiation.firstBuyerBidUsd)}</strong></div>
                <div className="ddv-side-row"><span>{tk("dealDetail.negotiation.discountGiven", "Discount given")}</span><strong className="muted">−{fmtUsd(data.negotiation.initialAskingUsd - data.totalValueUsd)}</strong></div>
                <div className="ddv-divider" />
                <div className="ddv-side-row big"><span>{tk("dealDetail.negotiation.finalTotal", "Final total")}</span><strong className="accent">{fmtUsd(data.totalValueUsd)}</strong></div>
              </Card>
              {data.fullNegotiationHref && (
                <Link to={data.fullNegotiationHref} className="ddv-btn-ghost-block">
                  <MessageIcon size={14} /> {tk("dealDetail.negotiation.openFull", "Open full negotiation")}
                </Link>
              )}
            </>
          ) : (
            <>
              <Card title={partyHeaderLabel.toUpperCase()} icon={UserIcon}>
                <div className="ddv-party">
                  <span className="ddv-party-av">{initials(data.party.name)}</span>
                  <div className="ddv-party-meta">
                    <strong>{data.party.name}</strong>
                    {data.party.country && (
                      <span>
                        <span className="ddv-flag">{data.party.flagEmoji ?? "📍"}</span>
                        {data.party.country}
                      </span>
                    )}
                  </div>
                </div>
                <button type="button" className="ddv-btn-ghost ddv-btn-block" onClick={stub(tk("dealDetail.toast.message", "Open chat (mock)"))}>
                  <MessageIcon size={14} /> {messagePartyLabel}
                </button>
              </Card>

              <Card title={tk("dealDetail.timeline.title", "QUICK TIMELINE")} icon={ClockIcon}>
                {data.timeline.map((s) => (
                  <div key={s.key} className="ddv-tl-row">
                    <span>{s.label}</span>
                    <span className={`ddv-tl-val ddv-tl-val--${s.tone ?? "muted"}`}>{s.value}</span>
                  </div>
                ))}
              </Card>
            </>
          )}
        </aside>
      </div>
    </div>
  );
}
