import { useEffect, useState } from "react";
import { useParams } from "react-router-dom";
import { supabase } from "@/integrations/supabase/client";

type SI = Record<string, any>;
type Req = Record<string, any>;

function fmtDate(iso: string | null | undefined): string {
  if (!iso) return "—";
  return new Date(iso).toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });
}

export default function ShippingInstructionsPrint() {
  const { requestId } = useParams<{ requestId: string }>();
  const [si, setSi] = useState<SI | null>(null);
  const [req, setReq] = useState<Req | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    (async () => {
      if (!requestId) return;
      const { data: r } = await supabase
        .from("shipping_instructions_requests")
        .select("*")
        .eq("id", requestId)
        .maybeSingle();
      if (!r) { setError("Shipping instructions not found."); setLoading(false); return; }
      setReq(r);
      const { data: s } = await supabase
        .from("shipping_instructions")
        .select("*")
        .eq("request_id", requestId)
        .order("created_at", { ascending: false })
        .limit(1)
        .maybeSingle();
      setSi(s as SI);
      setLoading(false);
      setTimeout(() => { try { window.print(); } catch { /* noop */ } }, 600);
    })();
  }, [requestId]);

  if (loading) return <Centered>Loading…</Centered>;
  if (error || !si) return <Centered>{error || "No shipping instructions submitted yet."}</Centered>;

  const docs: string[] = Array.isArray(si.documents_requested) ? si.documents_requested : [];
  const lines: string[] = Array.isArray(si.approved_shipping_lines) ? si.approved_shipping_lines : [];
  const status = String(req?.status ?? "received");
  const statusLabel = status === "approved" ? "Approved" : status === "received" ? "Received" : status;

  return (
    <div className="si-print-root">
      <style>{printCss}</style>
      <div className="si-print-toolbar no-print">
        <button onClick={() => window.print()} className="si-print-btn">📄 Print / Save as PDF</button>
        <span className="si-print-hint">Use your browser print dialog → Save as PDF</span>
      </div>

      <div className="si-print-page">
        <header className="si-print-header">
          <div className="si-print-brand">MUNDUS TRADE</div>
          <div className="si-print-title">SHIPPING INSTRUCTIONS</div>
        </header>

        <div className="si-print-meta">
          <div><span className="si-print-meta-lbl">Order</span><strong>{String(si.order_number ?? "—")}</strong></div>
          <div><span className="si-print-meta-lbl">Date</span><strong>{fmtDate(req?.submitted_at)}</strong></div>
          <div><span className="si-print-meta-lbl">Status</span><strong>{statusLabel}</strong></div>
        </div>

        <Section title="Buyer for Invoice">
          <Row k="Company" v={si.buyer_name} />
          <Row k="Address" v={si.buyer_address} />
        </Section>

        <Section title="Destination">
          <Row k="Port" v={si.port_of_destination} />
          <Row k="Country" v={si.country_of_destination} />
        </Section>

        <Section title="Consignee">
          <Row k="Name" v={si.consignee_name} />
          <Row k="Address" v={si.consignee_address} />
          <Row k="Phone" v={si.consignee_phone} />
        </Section>

        <Section title="BL Notify Party">
          <Row k="Name" v={si.notify_name} />
          <Row k="Address" v={si.notify_address} />
          <Row k="Phone" v={si.notify_phone} />
        </Section>

        <Section title="Documents Requested">
          <div className="si-print-chips">
            {docs.length === 0 ? <span className="si-print-muted">—</span> :
              docs.map((d) => <span key={d} className="si-print-chip">✓ {d}</span>)}
          </div>
        </Section>

        <Section title="Telex Release">
          <p className="si-print-p">{String(si.telex_release ?? "—")}</p>
        </Section>

        <Section title="Approved Shipping Lines">
          <p className="si-print-p">{lines.length ? lines.join(", ") : "—"}</p>
        </Section>

        {si.observations && (
          <Section title="Observations">
            <p className="si-print-p" style={{ whiteSpace: "pre-wrap" }}>{String(si.observations)}</p>
          </Section>
        )}

        <footer className="si-print-footer">
          Generated by Mundus Trade · mundustrade.com<br />
          This document is for shipping purposes only.
        </footer>
      </div>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="si-print-section">
      <h2 className="si-print-section-title">{title}</h2>
      <div className="si-print-section-body">{children}</div>
    </section>
  );
}

function Row({ k, v }: { k: string; v: unknown }) {
  return (
    <div className="si-print-row">
      <span className="si-print-row-k">{k}</span>
      <span className="si-print-row-v">{v ? String(v) : "—"}</span>
    </div>
  );
}

function Centered({ children }: { children: React.ReactNode }) {
  return (
    <div style={{ minHeight: "100vh", display: "flex", alignItems: "center", justifyContent: "center", padding: 32, fontFamily: "system-ui, sans-serif", color: "#6b7280" }}>
      {children}
    </div>
  );
}

const printCss = `
.si-print-root { background: #f3f4f6; min-height: 100vh; font-family: 'Inter', system-ui, -apple-system, sans-serif; color: #2a1a20; }
.si-print-toolbar { position: sticky; top: 0; background: white; padding: 12px 24px; border-bottom: 1px solid #e5e7eb; display: flex; align-items: center; gap: 12px; z-index: 10; }
.si-print-btn { background: #8B2252; color: white; border: none; padding: 8px 16px; border-radius: 6px; font-size: 13px; font-weight: 600; cursor: pointer; }
.si-print-hint { font-size: 12px; color: #6b7280; }
.si-print-page { max-width: 820px; margin: 24px auto; background: white; padding: 48px 56px; box-shadow: 0 1px 3px rgba(0,0,0,.08); border-radius: 4px; }
.si-print-header { text-align: center; padding-bottom: 16px; border-bottom: 3px solid #8B2252; margin-bottom: 24px; }
.si-print-brand { font-size: 13px; font-weight: 700; letter-spacing: .2em; color: #8B2252; margin-bottom: 6px; }
.si-print-title { font-size: 24px; font-weight: 700; letter-spacing: .04em; color: #2a1a20; }
.si-print-meta { display: flex; justify-content: space-between; gap: 16px; padding: 14px 18px; background: #fdf2f8; border-radius: 6px; margin-bottom: 24px; }
.si-print-meta > div { display: flex; flex-direction: column; gap: 2px; }
.si-print-meta-lbl { font-size: 10px; text-transform: uppercase; letter-spacing: .08em; color: #8B2252; font-weight: 700; }
.si-print-meta strong { font-size: 14px; color: #2a1a20; font-weight: 600; }
.si-print-section { margin-bottom: 18px; padding-bottom: 14px; border-bottom: 1px solid #f1f5f9; }
.si-print-section:last-of-type { border-bottom: none; }
.si-print-section-title { font-size: 11px; font-weight: 700; letter-spacing: .1em; text-transform: uppercase; color: #8B2252; margin: 0 0 8px; }
.si-print-row { display: flex; gap: 12px; padding: 3px 0; font-size: 13px; }
.si-print-row-k { color: #6b7280; min-width: 110px; }
.si-print-row-v { color: #2a1a20; flex: 1; }
.si-print-p { margin: 0; font-size: 13px; color: #2a1a20; }
.si-print-muted { color: #9ca3af; font-size: 13px; }
.si-print-chips { display: flex; flex-wrap: wrap; gap: 6px; }
.si-print-chip { background: #fdf2f8; color: #8B2252; padding: 4px 10px; border-radius: 999px; font-size: 12px; font-weight: 500; }
.si-print-footer { margin-top: 32px; padding-top: 16px; border-top: 1px solid #f1f5f9; text-align: center; font-size: 11px; color: #9ca3af; line-height: 1.6; }

@media print {
  body { background: white !important; }
  .no-print { display: none !important; }
  .si-print-root { background: white; }
  .si-print-page { box-shadow: none; margin: 0; max-width: none; padding: 24px 32px; }
  .si-print-section { page-break-inside: avoid; }
  @page { margin: 14mm; }
}
`;