ALTER TABLE public.countries ADD COLUMN IF NOT EXISTS french_name TEXT;
ALTER TABLE public.countries ADD COLUMN IF NOT EXISTS chinese_name TEXT;

-- Populate French and Chinese names for top destination/origin countries
UPDATE public.countries SET french_name = v.fr, chinese_name = v.zh
FROM (VALUES
  ('US','États-Unis','美国'),
  ('BR','Brésil','巴西'),
  ('CN','Chine','中国'),
  ('AE','Émirats arabes unis','阿联酋'),
  ('SA','Arabie saoudite','沙特阿拉伯'),
  ('AR','Argentine','阿根廷'),
  ('EG','Égypte','埃及'),
  ('PS','Palestine','巴勒斯坦'),
  ('UY','Uruguay','乌拉圭'),
  ('PY','Paraguay','巴拉圭'),
  ('AU','Australie','澳大利亚'),
  ('NZ','Nouvelle-Zélande','新西兰'),
  ('CA','Canada','加拿大'),
  ('MX','Mexique','墨西哥'),
  ('CL','Chili','智利'),
  ('PE','Pérou','秘鲁'),
  ('CO','Colombie','哥伦比亚'),
  ('GB','Royaume-Uni','英国'),
  ('FR','France','法国'),
  ('DE','Allemagne','德国'),
  ('IT','Italie','意大利'),
  ('ES','Espagne','西班牙'),
  ('PT','Portugal','葡萄牙'),
  ('NL','Pays-Bas','荷兰'),
  ('BE','Belgique','比利时'),
  ('JP','Japon','日本'),
  ('KR','Corée du Sud','韩国'),
  ('HK','Hong Kong','香港'),
  ('SG','Singapour','新加坡'),
  ('PH','Philippines','菲律宾'),
  ('VN','Vietnam','越南'),
  ('TH','Thaïlande','泰国'),
  ('MY','Malaisie','马来西亚'),
  ('ID','Indonésie','印度尼西亚'),
  ('IN','Inde','印度'),
  ('TR','Turquie','土耳其'),
  ('IL','Israël','以色列'),
  ('JO','Jordanie','约旦'),
  ('LB','Liban','黎巴嫩'),
  ('KW','Koweït','科威特'),
  ('QA','Qatar','卡塔尔'),
  ('OM','Oman','阿曼'),
  ('BH','Bahreïn','巴林'),
  ('IQ','Irak','伊拉克'),
  ('MA','Maroc','摩洛哥'),
  ('DZ','Algérie','阿尔及利亚'),
  ('TN','Tunisie','突尼斯'),
  ('LY','Libye','利比亚'),
  ('ZA','Afrique du Sud','南非'),
  ('NG','Nigeria','尼日利亚'),
  ('RU','Russie','俄罗斯')
) AS v(iso,fr,zh)
WHERE public.countries.iso_code = v.iso;