
-- US Pork IMPS (region='us')
INSERT INTO public.cuts (name, category, region, product_number, imps_number, bone_spec, unit_weight, is_active) VALUES
('Carcass','Pork','us',400,'400','Bone-In','Kg',true),
('Roasting Pig','Pork','us',400,'400A','Bone-In','Kg',true),
('Leg (Fresh Ham)','Pork','us',401,'401','Bone-In','Kg',true),
('Leg (Fresh Ham), Short Shank','Pork','us',401,'401A','Bone-In','Kg',true),
('Leg (Fresh Ham), Semi-Boneless','Pork','us',401,'401C','Boneless','Kg',true),
('Leg, Hind Shank','Pork','us',401,'401D','Bone-In','Kg',true),
('Leg (Fresh Ham), Skinned','Pork','us',402,'402','Bone-In','Kg',true),
('Leg (Fresh Ham), Skinned, Short Shank','Pork','us',402,'402A','Bone-In','Kg',true),
('Leg (Fresh Ham), Boneless','Pork','us',402,'402B','Boneless','Kg',true),
('Leg (Fresh Ham), Boneless, Short Shank, Trimmed','Pork','us',402,'402C','Boneless','Kg',true),
('Leg (Fresh Ham), Outside','Pork','us',402,'402D','Boneless','Kg',true),
('Leg (Fresh Ham), Outside, Trimmed, Shank Removed','Pork','us',402,'402E','Boneless','Kg',true),
('Leg (Fresh Ham), Inside','Pork','us',402,'402F','Boneless','Kg',true),
('Leg (Fresh Ham), TBS, 3-Way, Boneless','Pork','us',402,'402G','Boneless','Kg',true),
('Shoulder','Pork','us',403,'403','Bone-In','Kg',true),
('Shoulder, Outside','Pork','us',403,'403B','Bone-In','Kg',true),
('Shoulder, Inside, Boneless','Pork','us',403,'403C','Boneless','Kg',true),
('Shoulder, Skinned','Pork','us',404,'404','Bone-In','Kg',true),
('Shoulder, Picnic','Pork','us',405,'405','Bone-In','Kg',true),
('Shoulder, Picnic, Boneless','Pork','us',405,'405A','Boneless','Kg',true),
('Shoulder, Picnic, Cushion, Boneless','Pork','us',405,'405B','Boneless','Kg',true),
('Shoulder, Pectoral Meat','Pork','us',405,'405C','Boneless','Kg',true),
('Shoulder, Boston Butt, Bone In','Pork','us',406,'406','Bone-In','Kg',true),
('Shoulder, Boston Butt, Boneless','Pork','us',406,'406A','Boneless','Kg',true),
('Shoulder, Boston Butt, Boneless, Special','Pork','us',406,'406B','Boneless','Kg',true),
('Shoulder Butt, Cellar Trimmed, Boneless','Pork','us',407,'407','Boneless','Kg',true),
('Belly','Pork','us',408,'408','Boneless','Kg',true),
('Fat Back','Pork','us',408,'408A','Boneless','Kg',true),
('Belly, Skinless','Pork','us',409,'409','Boneless','Kg',true),
('Belly, Single Ribbed, Skinless','Pork','us',409,'409A','Boneless','Kg',true),
('Belly, Center-Cut, Skinless','Pork','us',409,'409B','Boneless','Kg',true),
('Loin, Bone In','Pork','us',410,'410','Bone-In','Kg',true),
('Loin, Sirloin End, Bone In','Pork','us',410,'410A','Bone-In','Kg',true),
('Loin, Rib End, Bone In','Pork','us',410,'410B','Bone-In','Kg',true),
('Loin, Bone In, Bladeless','Pork','us',411,'411','Bone-In','Kg',true),
('Loin, Bone In, Center-Cut, 8 Ribs','Pork','us',412,'412','Bone-In','Kg',true),
('Loin, Bone In, Center-Cut, 8 Ribs, Chine Bone Off','Pork','us',412,'412A','Bone-In','Kg',true),
('Loin, Boneless, Center-Cut, 8 Ribs','Pork','us',412,'412B','Boneless','Kg',true),
('Loin, Bone In, Center-Cut, 11 Ribs','Pork','us',412,'412C','Bone-In','Kg',true),
('Loin, Bone In, Center-Cut, 11 Ribs, Chine Bone Off','Pork','us',412,'412D','Bone-In','Kg',true),
('Loin, Boneless, Center-Cut, 11 Ribs','Pork','us',412,'412E','Boneless','Kg',true),
('Loin, Center-Cut, Rib End (Rack)','Pork','us',412,'412G','Bone-In','Kg',true),
('Loin, Boneless','Pork','us',413,'413','Boneless','Kg',true),
('Loin, Boneless, Roast','Pork','us',413,'413A','Boneless','Kg',true),
('Loin, Boneless, Special','Pork','us',413,'413B','Boneless','Kg',true),
('Loin, Loin Eye','Pork','us',413,'413C','Boneless','Kg',true),
('Loin, Canadian Back','Pork','us',414,'414','Boneless','Kg',true),
('Tenderloin','Pork','us',415,'415','Boneless','Kg',true),
('Tenderloin, Side Muscle Off','Pork','us',415,'415A','Boneless','Kg',true),
('Spareribs','Pork','us',416,'416','Bone-In','Kg',true),
('Spareribs, St. Louis Style','Pork','us',416,'416A','Bone-In','Kg',true),
('Spareribs, Brisket Bones','Pork','us',416,'416B','Bone-In','Kg',true),
('Spareribs, Breast Off','Pork','us',416,'416C','Bone-In','Kg',true),
('Breast Bones','Pork','us',416,'416D','Bone-In','Kg',true),
('Shoulder Hocks','Pork','us',417,'417','Offals','Kg',true),
('Leg (Fresh Ham) Hocks','Pork','us',417,'417A','Offals','Kg',true),
('Trimmings','Pork','us',418,'418','Boneless','Kg',true),
('Pig''s Feet, Front','Pork','us',420,'420','Offals','Kg',true),
('Neck Bones','Pork','us',421,'421','Offals','Kg',true),
('Loin, Back Ribs','Pork','us',422,'422','Bone-In','Kg',true),
('Loin, Country-Style Ribs','Pork','us',423,'423','Bone-In','Kg',true),
('Loin, Riblet','Pork','us',424,'424','Bone-In','Kg',true),
('Pork for Kabobs','Pork','us',435,'435B','Boneless','Kg',true),
('Caul Fat','Pork','us',472,'472','Offals','Kg',true),
('Ground Pork','Pork','us',496,'496','Boneless','Kg',true),
('Steak, Cubed','Pork','us',1400,'1400','Boneless','Kg',true),
('Steaks, Cubed, Special','Pork','us',1401,'1401','Boneless','Kg',true),
('Cutlets','Pork','us',1402,'1402','Boneless','Kg',true),
('Boston Butt Steaks','Pork','us',1406,'1406','Bone-In','Kg',true),
('Shoulder Butt Steaks, Boneless','Pork','us',1407,'1407','Boneless','Kg',true),
('Loin Chops','Pork','us',1410,'1410','Bone-In','Kg',true),
('Loin, Rib Chops','Pork','us',1410,'1410A','Bone-In','Kg',true),
('Loin, End Chops','Pork','us',1410,'1410B','Bone-In','Kg',true),
('Loin Chops, Bladeless','Pork','us',1411,'1411','Bone-In','Kg',true),
('Loin Chops, Center-Cut','Pork','us',1412,'1412','Bone-In','Kg',true),
('Loin Chops, Center-Cut, Chine Bone Off','Pork','us',1412,'1412A','Bone-In','Kg',true),
('Loin Chops, Center-Cut, Boneless','Pork','us',1412,'1412B','Boneless','Kg',true),
('Loin Chops, Center-Cut, One Muscle, Boneless','Pork','us',1412,'1412E','Boneless','Kg',true),
('Loin Chops, Boneless','Pork','us',1413,'1413','Boneless','Kg',true),
('Loin, End Chops, Boneless','Pork','us',1413,'1413B','Boneless','Kg',true),
('Steaks, Flaked and Formed, Frozen','Pork','us',1438,'1438','Boneless','Kg',true),
('Sandwich Steaks, Flaked, Chopped, Formed, and Wafer Sliced, Frozen','Pork','us',1438,'1438A','Boneless','Kg',true),
('Coarse Chopped Pork','Pork','us',1495,'1495','Boneless','Kg',true),
('Ground Pork Patties','Pork','us',1496,'1496','Boneless','Kg',true)
ON CONFLICT (name, category, region) DO NOTHING;

-- Global Pork offals
INSERT INTO public.cuts (name, category, region, bone_spec, unit_weight, is_active) VALUES
('Pork Feet','Pork','global','Offals','Kg',true),
('Pork Neck Bones','Pork','global','Offals','Kg',true),
('Pork Hocks','Pork','global','Offals','Kg',true),
('Pork Tongue','Pork','global','Offals','Kg',true),
('Pork Ears','Pork','global','Offals','Kg',true),
('Pork Snout','Pork','global','Offals','Kg',true),
('Pork Stomach','Pork','global','Offals','Kg',true),
('Pork Intestines','Pork','global','Offals','Kg',true),
('Pork Liver','Pork','global','Offals','Kg',true),
('Pork Heart','Pork','global','Offals','Kg',true),
('Pork Kidney','Pork','global','Offals','Kg',true),
('Pork Caul Fat','Pork','global','Offals','Kg',true),
('Pork Tail','Pork','global','Offals','Kg',true),
('Pork Jowl','Pork','global','Offals','Kg',true),
('Pork Mask','Pork','global','Offals','Kg',true),
('Pork Uterus','Pork','global','Offals','Kg',true),
('Pork Rectum','Pork','global','Offals','Kg',true)
ON CONFLICT (name, category, region) DO NOTHING;
